import { useCallback, useEffect, useMemo, useState, type FormEvent } from 'react';
import type { UserProfile } from '../../domain/profile/profile';
import { TrainingService } from '../../application/training/training-service';
import { normalizeExerciseName, searchExercises } from '../../domain/training/exercise-library';
import { suggestDoubleProgression } from '../../domain/training/progression';
import { currentPlanVersion, DAY_LABELS, EQUIPMENT_LABELS, MUSCLE_LABELS, sessionVolume, TRAINING_DAYS, type Equipment, type Exercise, type ExperienceLevel, type MuscleGroup, type TrainingDay, type TrainingGoal, type TrainingLocation, type TrainingProfile, type WorkoutPlan, type WorkoutSession, type WorkoutSetLog, type WorkoutTemplate } from '../../domain/training/training';
import { toLocalDateKey } from '../../domain/shared/local-date';
import { repositories } from '../../infrastructure/repositories';
import { DefynSelect } from '../../shared/components/DefynSelect';
import { ExerciseIllustration } from './ExerciseIllustration';
import { Button } from '../../shared/components/Button';
import { useDocumentScrollLock } from '../../shared/hooks/use-document-scroll-lock';
import { resolveTrainingHomeState } from './training-home-state';
import { GymMode } from './GymMode';
import { calculateExerciseRecords, formatSet } from '../../domain/training/workout-records';
import { createUuid } from '../../shared/ids/create-uuid';
import './training-workspace.css';

const service = new TrainingService(repositories.trainingProfiles, repositories.exercises, repositories.workoutPlans, repositories.workoutSessions);
type TrainingTab = 'today' | 'plan' | 'exercises' | 'history' | 'profile';
const tabs: { id: TrainingTab; label: string }[] = [{ id: 'today', label: 'Hoje' }, { id: 'plan', label: 'Minha ficha' }, { id: 'exercises', label: 'Exercícios' }, { id: 'history', label: 'Histórico' }];

export function TrainingWorkspace({ profile, revision, onChanged, onNotice }: { profile: UserProfile; revision: number; onChanged: () => void; onNotice: (message: string) => void }) {
  const [trainingProfile, setTrainingProfile] = useState<TrainingProfile>();
  const [plan, setPlan] = useState<WorkoutPlan>();
  const [sessions, setSessions] = useState<WorkoutSession[]>([]);
  const [activeSession, setActiveSession] = useState<WorkoutSession>();
  const [exercises, setExercises] = useState<Exercise[]>([]);
  const [favorites, setFavorites] = useState<Set<string>>(new Set());
  const [tab, setTab] = useState<TrainingTab>('today');
  const [showSetup, setShowSetup] = useState(false);
  const [sessionOpen, setSessionOpen] = useState(false);
  const [manualPickerOpen, setManualPickerOpen] = useState(false);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');

  const load = useCallback(async () => {
    try {
      const [nextProfile, nextPlan, nextSessions, nextActive, nextExercises, nextFavorites] = await Promise.all([
        repositories.trainingProfiles.get(profile.id), repositories.workoutPlans.getActive(profile.id), repositories.workoutSessions.list(profile.id), repositories.workoutSessions.getActive(profile.id), repositories.exercises.list(profile.id), repositories.exercises.listFavorites(profile.id),
      ]);
      setTrainingProfile(nextProfile); setPlan(nextPlan); setSessions(nextSessions); setActiveSession(nextActive); setSessionOpen(Boolean(nextActive)); setExercises(nextExercises); setFavorites(new Set(nextFavorites.map((item) => item.exerciseId))); setError('');
    } catch (caught) { setError(caught instanceof Error ? caught.message : 'Não foi possível abrir seus treinos.'); }
    finally { setLoading(false); }
  }, [profile.id]);

  useEffect(() => { queueMicrotask(() => void load()); }, [load, revision]);
  async function changed(message?: string) { await load(); onChanged(); if (message) onNotice(message); }
  async function startTemplate(template: WorkoutTemplate, message: string) { if (!plan) return; const started = await service.startSession(profile.id, plan.id, template.id); await changed(started.templateId === template.id ? message : `Já existe um treino em andamento: ${started.templateName}. Ele foi retomado sem criar uma sessão duplicada.`); setManualPickerOpen(false); setSessionOpen(true); }

  if (loading) return <div className="training-loading" aria-label="Carregando treinos"><span /><span /><span /></div>;
  if (error) return <div className="page-state error-state" role="alert"><strong>Treinos indisponíveis.</strong><p>{error}</p><button onClick={() => void load()}>Tentar novamente</button></div>;
  if (!trainingProfile) return showSetup ? <TrainingSetup profileId={profile.id} onSaved={() => changed('Perfil de treino criado.')} /> : <div className="training-page page-container"><header className="training-header"><div><span className="page-eyebrow">Caderno inteligente de academia</span><h1>Treinos</h1><p>Saiba o que fazer hoje e registre cada série no aparelho.</p></div></header><section className="training-state-card no-plan"><div><span>Sem ficha</span><h2>Você ainda não possui ficha.</h2><p>Crie sua configuração inicial para organizar os treinos da semana.</p></div><Button onClick={() => setShowSetup(true)}>Criar ficha <span aria-hidden="true">↗</span></Button></section></div>;
  if (activeSession && sessionOpen) return <GymMode profileId={profile.id} session={activeSession} exercises={exercises} onChanged={() => changed()} onFinished={(message) => { setSessionOpen(false); setTab('today'); void changed(message); }} onNotice={onNotice} />;

  return <div className="training-page page-container">
    <header className="training-header"><div><span className="page-eyebrow">Caderno inteligente de academia</span><h1>Treinos</h1><p>Ficha, cargas e histórico de {profile.name}, disponíveis offline.</p></div><button className="training-settings-button" onClick={() => setTab('profile')}>Configurar perfil</button></header>
    <nav className="training-tabs" aria-label="Áreas de treino">{tabs.map((item) => <button key={item.id} className={tab === item.id ? 'active' : ''} aria-current={tab === item.id ? 'page' : undefined} onClick={() => setTab(item.id)}>{item.label}</button>)}</nav>
    {tab === 'today' && <TrainingHome trainingProfile={trainingProfile} plan={plan} sessions={sessions} activeSession={activeSession} exercises={exercises} onStart={(template) => startTemplate(template, 'Treino iniciado. Cada série será salva neste dispositivo.')} onChooseManual={() => setManualPickerOpen(true)} onContinue={() => setSessionOpen(true)} onOpenPlan={() => setTab('plan')} onOpenHistory={() => setTab('history')} />}
    {tab === 'plan' && <PlanEditor key={`${plan?.id ?? 'empty'}-${plan?.currentVersion ?? 0}`} profileId={profile.id} trainingProfile={trainingProfile} plan={plan} exercises={exercises} onSaved={(message) => changed(message)} />}
    {tab === 'exercises' && <ExerciseLibrary profileId={profile.id} exercises={exercises} favorites={favorites} onChanged={(message) => changed(message)} />}
    {tab === 'history' && <TrainingHistory profileId={profile.id} sessions={sessions} exercises={exercises} />}
    {tab === 'profile' && <TrainingSetup profileId={profile.id} existing={trainingProfile} compact onSaved={() => { setTab('today'); void changed('Preferências de treino atualizadas.'); }} />}
    {manualPickerOpen && plan && <WorkoutPicker templates={currentPlanVersion(plan).templates} onClose={() => setManualPickerOpen(false)} onStart={(template) => startTemplate(template, 'Sessão avulsa iniciada. Sua ficha e o planejamento semanal não foram alterados.')} />}
  </div>;
}

function TrainingSetup({ profileId, existing, compact = false, onSaved }: { profileId: string; existing?: TrainingProfile; compact?: boolean; onSaved: () => void }) {
  const [goal, setGoal] = useState<TrainingGoal>(existing?.primaryGoal ?? 'hypertrophy');
  const [experience, setExperience] = useState<ExperienceLevel>(existing?.experienceLevel ?? 'beginner');
  const [days, setDays] = useState(existing?.availableDaysPerWeek ?? 3);
  const [selectedDays, setSelectedDays] = useState<TrainingDay[]>(existing?.preferredTrainingDays ?? ['monday', 'wednesday', 'friday']);
  const [minutes, setMinutes] = useState(existing?.averageSessionMinutes ?? 60);
  const [location, setLocation] = useState<TrainingLocation>(existing?.trainingLocation ?? 'gym');
  const [equipment, setEquipment] = useState<Equipment[]>(existing?.availableEquipment ?? []);
  const [limitations, setLimitations] = useState(existing?.informedLimitations ?? '');
  const [busy, setBusy] = useState(false); const [error, setError] = useState('');
  function toggleDay(day: TrainingDay) { setSelectedDays((current) => current.includes(day) ? current.filter((item) => item !== day) : [...current, day].sort((a, b) => TRAINING_DAYS.indexOf(a) - TRAINING_DAYS.indexOf(b))); }
  function toggleEquipment(item: Equipment) { setEquipment((current) => current.includes(item) ? current.filter((value) => value !== item) : [...current, item]); }
  async function save(createPlan: boolean, manual = false) {
    setBusy(true); setError('');
    try {
      const chosenDays = selectedDays.slice(0, days);
      const result = await service.setupProfile({ profileId, primaryGoal: goal, experienceLevel: experience, availableDaysPerWeek: days, preferredTrainingDays: chosenDays.length === days ? chosenDays : TRAINING_DAYS.filter((day) => day !== 'sunday').slice(0, days), averageSessionMinutes: minutes, trainingLocation: location, availableEquipment: equipment, preferredExercises: existing?.preferredExercises ?? [], avoidedExercises: existing?.avoidedExercises ?? [], informedLimitations: limitations.trim() || undefined, weightUnit: existing?.weightUnit ?? 'kg', defaultLoadIncrement: existing?.defaultLoadIncrement ?? 2.5, advancedMode: existing?.advancedMode ?? false }, createPlan);
      if (manual && !result.plan) {
        const timestamp = new Date().toISOString();
        await repositories.workoutPlans.save({ id: createUuid(), profileId, name: 'Minha ficha', goal, status: 'active', startDate: timestamp.slice(0, 10), currentVersion: 1, versions: [{ version: 1, createdAt: timestamp, note: 'Ficha criada manualmente', templates: [{ id: createUuid(), name: 'Treino A', focus: 'Personalizado', scheduledDay: chosenDays[0] ?? 'monday', approximateMinutes: minutes, exercises: [] }] }], createdAt: timestamp, updatedAt: timestamp });
      }
      onSaved();
    } catch (caught) { setError(caught instanceof Error ? caught.message : 'Não foi possível salvar o perfil de treino.'); }
    finally { setBusy(false); }
  }
  return <section className={`training-setup ${compact ? 'compact' : ''}`}><header><span className="page-eyebrow">Configuração editável</span><h2>{existing ? 'Seu perfil de treino' : 'Seu treino começa aqui.'}</h2><p>O DEFYN organiza referências a partir da sua rotina. Limitações informadas sempre exigem revisão apropriada.</p></header>
    <div className="training-setup-grid">
      <label>Objetivo<DefynSelect label="Objetivo do treino" value={goal} onChange={(value) => setGoal(value as TrainingGoal)} options={[{ value: 'hypertrophy', label: 'Hipertrofia' }, { value: 'strength', label: 'Força' }, { value: 'conditioning', label: 'Condicionamento' }, { value: 'body-composition', label: 'Composição corporal' }, { value: 'custom', label: 'Personalizado' }]} /></label>
      <label>Experiência<DefynSelect label="Nível de experiência" value={experience} onChange={(value) => setExperience(value as ExperienceLevel)} options={[{ value: 'beginner', label: 'Iniciante · construindo base' }, { value: 'intermediate', label: 'Intermediário · rotina consistente' }, { value: 'advanced', label: 'Avançado · experiência consolidada' }]} /></label>
      <label>Dias por semana<DefynSelect label="Dias disponíveis por semana" value={String(days)} onChange={(value) => setDays(Number(value))} options={[1,2,3,4,5,6].map((value) => ({ value: String(value), label: `${value} ${value === 1 ? 'dia' : 'dias'}` }))} /></label>
      <label>Duração de referência<DefynSelect label="Duração média da sessão" value={String(minutes)} onChange={(value) => setMinutes(Number(value))} options={[30,45,60,75,90].map((value) => ({ value: String(value), label: `${value} minutos` }))} /></label>
      <label>Local<DefynSelect label="Local de treino" value={location} onChange={(value) => setLocation(value as TrainingLocation)} options={[{ value: 'gym', label: 'Academia' }, { value: 'home', label: 'Casa' }, { value: 'both', label: 'Ambos' }]} /></label>
      <label>Limitações informadas<textarea value={limitations} onChange={(event) => setLimitations(event.target.value)} placeholder="Opcional. Não será interpretado como diagnóstico." /></label>
    </div>
    <fieldset className="training-chip-field"><legend>Dias preferidos</legend><div>{TRAINING_DAYS.map((day) => <button type="button" key={day} className={selectedDays.includes(day) ? 'selected' : ''} aria-pressed={selectedDays.includes(day)} onClick={() => toggleDay(day)}>{DAY_LABELS[day]}</button>)}</div></fieldset>
    <fieldset className="training-chip-field"><legend>Equipamentos disponíveis</legend><p>Na academia, deixe vazio para considerar o catálogo completo.</p><div>{(Object.keys(EQUIPMENT_LABELS) as Equipment[]).map((item) => <button type="button" key={item} className={equipment.includes(item) ? 'selected' : ''} aria-pressed={equipment.includes(item)} onClick={() => toggleEquipment(item)}>{EQUIPMENT_LABELS[item]}</button>)}</div></fieldset>
    {error && <p className="inline-error" role="alert">{error}</p>}
    <footer>{existing ? <button className="training-primary" disabled={busy} onClick={() => void save(false)}>{busy ? 'Salvando…' : 'Salvar preferências'}</button> : <><button className="training-secondary" disabled={busy} onClick={() => void save(false, true)}>Montar manualmente</button><button className="training-primary" disabled={busy} onClick={() => void save(true)}>{busy ? 'Criando…' : 'Criar plano inicial'}</button></>}</footer>
  </section>;
}

function TrainingHome({ trainingProfile, plan, sessions, activeSession, exercises, onStart, onChooseManual, onContinue, onOpenPlan, onOpenHistory }: { trainingProfile: TrainingProfile; plan?: WorkoutPlan; sessions: WorkoutSession[]; activeSession?: WorkoutSession; exercises: Exercise[]; onStart: (template: WorkoutTemplate) => Promise<void>; onChooseManual: () => void; onContinue: () => void; onOpenPlan: () => void; onOpenHistory: () => void }) {
  const version = plan ? currentPlanVersion(plan) : undefined;
  const today = TRAINING_DAYS[(new Date().getDay() + 6) % 7] ?? 'monday';
  const template = version?.templates.find((item) => item.scheduledDay === today);
  const completedToday = sessions.find((item) => item.localDate === toLocalDateKey(new Date()) && item.status === 'completed');
  let nextTemplate: { template: WorkoutTemplate; offset: number } | undefined;
  if (version) for (let offset = 1; offset <= 7; offset += 1) {
    const day = TRAINING_DAYS[(TRAINING_DAYS.indexOf(today) + offset) % 7];
    const candidate = version.templates.find((item) => item.scheduledDay === day);
    if (candidate) { nextTemplate = { template: candidate, offset }; break; }
  }
  const state = resolveTrainingHomeState({ hasPlan: Boolean(plan && version), active: activeSession ? { name: activeSession.templateName, currentExercise: activeSession.currentExerciseIndex + 1, exerciseCount: activeSession.exercises.length } : undefined, today: template ? { name: template.name, exerciseCount: template.exercises.length, minutes: template.approximateMinutes } : undefined, completed: completedToday ? { name: completedToday.templateName, exerciseCount: completedToday.exercises.length, minutes: durationMinutes(completedToday) } : undefined, next: nextTemplate ? { name: nextTemplate.template.name, dayLabel: nextTemplate.offset === 1 ? 'amanhã' : DAY_LABELS[nextTemplate.template.scheduledDay] } : undefined });
  const act = () => { if (state.kind === 'active') onContinue(); else if (state.kind === 'planned' && template) void onStart(template); else if (state.kind === 'completed') onOpenHistory(); else if (state.kind === 'rest') onChooseManual(); else onOpenPlan(); };
  return <div className="training-home">
    <section className={`training-state-card ${state.kind}`}><div><span>{state.eyebrow}</span><h2>{state.title}</h2>{'detail' in state && <p>{state.kind === 'planned' && template ? `${template.focus} · ${state.detail}` : state.detail}</p>}</div><Button onClick={act}>{state.action} <span aria-hidden="true">↗</span></Button></section>
    {template && <section className="today-exercise-list"><header><div><span className="page-eyebrow">Antes de começar</span><h2>Exercícios de hoje</h2></div><span>{template.exercises.length} exercícios · ~{template.approximateMinutes} min</span></header><div>{template.exercises.map((item) => { const exercise = exercises.find((candidate) => candidate.id === item.exerciseId); return <article key={item.id}><ExerciseIllustration exercise={exercise} /><div><strong>{exercise?.name ?? 'Exercício indisponível'}</strong><span>{exercise ? `${MUSCLE_LABELS[exercise.primaryMuscle]} · ${exercise.equipment.map((value) => EQUIPMENT_LABELS[value]).join(', ')}` : 'Revise sua ficha'}</span></div><dl><div><dt>Séries</dt><dd>{item.workingSets}</dd></div><div><dt>Alvo</dt><dd>{item.target.minimum}{item.target.maximum !== item.target.minimum ? `–${item.target.maximum}` : ''} {item.target.metric === 'seconds' ? 's' : 'reps'}</dd></div><div><dt>Descanso</dt><dd>{item.restSeconds}s</dd></div></dl></article>; })}</div></section>}
    {plan && version && <section className="training-week"><header><div><span className="page-eyebrow">Minha semana</span><h2>{plan.name}</h2></div><Button variant="secondary" compact className="training-plan-edit" onClick={onOpenPlan}>Editar ficha</Button></header><div>{TRAINING_DAYS.map((day) => { const item = version.templates.find((candidate) => candidate.scheduledDay === day); const done = Boolean(item && sessions.some((session) => session.localDate && localDay(session.localDate) === day && session.status === 'completed' && session.templateId === item.id)); return <article key={day} className={day === today ? 'today' : ''}><span>{DAY_LABELS[day]}</span><strong>{item?.name ?? 'Descanso'}</strong><small>{done ? 'Concluído' : item?.focus ?? 'Recuperação'}</small></article>; })}</div></section>}
    <aside className="training-responsibility"><strong>Plano, não prescrição.</strong><p>Ajuste exercícios, cargas e volume à sua realidade. Dor ou restrição relevante pede revisão apropriada.</p><span>{trainingProfile.availableDaysPerWeek}x por semana · {trainingProfile.averageSessionMinutes} min</span></aside>
  </div>;
}

function localDay(localDate: string): TrainingDay { const date = new Date(`${localDate}T12:00:00`); return TRAINING_DAYS[(date.getDay() + 6) % 7] ?? 'monday'; }

function WorkoutPicker({ templates, onClose, onStart }: { templates: WorkoutTemplate[]; onClose: () => void; onStart: (template: WorkoutTemplate) => Promise<void> }) {
  const [selectedId, setSelectedId] = useState('');
  const [busy, setBusy] = useState(false);
  const selected = templates.find((template) => template.id === selectedId);
  useDocumentScrollLock();
  return <div className="training-modal-backdrop" onMouseDown={(event) => { if (event.target === event.currentTarget) onClose(); }}><section className="training-modal workout-picker" role="dialog" aria-modal="true" aria-label="Escolher treino"><header><div><span className="page-eyebrow">Sessão avulsa</span><h2>Escolher treino</h2></div><button type="button" onClick={onClose} aria-label="Fechar">×</button></header><p>Escolha qualquer treino da ficha. Isso não altera seus dias planejados.</p><div className="workout-picker-list">{templates.map((template) => <button type="button" key={template.id} className={selectedId === template.id ? 'selected' : ''} aria-pressed={selectedId === template.id} onClick={() => setSelectedId(template.id)}><span><strong>{template.name}</strong><small>{template.focus}</small></span><b>{template.exercises.length} exercícios · ~{template.approximateMinutes} min</b></button>)}</div><footer><button type="button" className="training-secondary" onClick={onClose}>Cancelar</button><button type="button" className="training-primary" disabled={!selected || busy} onClick={() => { if (!selected) return; setBusy(true); void onStart(selected).finally(() => setBusy(false)); }}>{busy ? 'Iniciando…' : 'Iniciar treino'}</button></footer></section></div>;
}

function PlanEditor({ profileId, trainingProfile, plan, exercises, onSaved }: { profileId: string; trainingProfile: TrainingProfile; plan?: WorkoutPlan; exercises: Exercise[]; onSaved: (message: string) => void }) {
  const [draft, setDraft] = useState<WorkoutTemplate[]>(plan ? structuredClone(currentPlanVersion(plan).templates) : []);
  const [selected, setSelected] = useState(0); const [adding, setAdding] = useState(false); const [busy, setBusy] = useState(false);
  const template = draft[selected];
  function updateTemplate(change: Partial<WorkoutTemplate>) { setDraft((current) => current.map((item, index) => index === selected ? { ...item, ...change } : item)); }
  function updateExercise(index: number, change: Record<string, unknown>) { if (!template) return; updateTemplate({ exercises: template.exercises.map((item, current) => current === index ? { ...item, ...change } : item) }); }
  function move(index: number, delta: number) { if (!template) return; updateTemplate({ exercises: TrainingService.reorder(template.exercises, index, Math.max(0, Math.min(template.exercises.length - 1, index + delta))) }); }
  function addExercise(exercise: Exercise) { if (!template || template.exercises.some((item) => item.exerciseId === exercise.id)) return; const isTime = exercise.metric === 'seconds'; updateTemplate({ exercises: [...template.exercises, { id: createUuid(), exerciseId: exercise.id, order: template.exercises.length, setType: 'working', workingSets: trainingProfile.experienceLevel === 'beginner' ? 3 : 4, target: isTime ? { metric: 'seconds', minimum: 30, maximum: 60 } : { metric: 'reps', minimum: 8, maximum: 12 }, loadUnit: exercise.equipment.includes('bodyweight') ? 'none' : trainingProfile.weightUnit, restSeconds: exercise.movementPattern === 'isolation' ? 60 : 90, loadIncrement: trainingProfile.defaultLoadIncrement }] }); setAdding(false); }
  async function save() { if (!plan) return; setBusy(true); try { await service.saveEditedPlan(profileId, plan.id, draft); onSaved('Nova versão da ficha salva. O histórico anterior permanece intacto.'); } finally { setBusy(false); } }
  if (!plan || !template) return <div className="training-empty"><h2>Nenhuma ficha ativa.</h2><p>Volte ao perfil de treino para criar seu plano inicial.</p></div>;
  return <div className="plan-editor"><aside className="plan-template-list"><header><span>Divisão semanal</span><button onClick={() => setDraft((current) => [...current, { id: createUuid(), name: `Treino ${String.fromCharCode(65 + current.length)}`, focus: 'Personalizado', scheduledDay: TRAINING_DAYS.find((day) => !current.some((item) => item.scheduledDay === day)) ?? 'monday', approximateMinutes: trainingProfile.averageSessionMinutes, exercises: [] }])}>+</button></header>{draft.map((item, index) => <button key={item.id} className={selected === index ? 'active' : ''} onClick={() => setSelected(index)}><span>{DAY_LABELS[item.scheduledDay]}</span><strong>{item.name}</strong><small>{item.exercises.length} exercícios</small></button>)}</aside>
    <section className="plan-workspace"><header><div><input aria-label="Nome do treino" value={template.name} onChange={(event) => updateTemplate({ name: event.target.value })} /><input aria-label="Foco do treino" value={template.focus} onChange={(event) => updateTemplate({ focus: event.target.value })} /></div><DefynSelect label="Dia da semana" value={template.scheduledDay} onChange={(value) => updateTemplate({ scheduledDay: value as TrainingDay })} options={TRAINING_DAYS.map((day) => ({ value: day, label: DAY_LABELS[day] }))} /></header>
      <div className="prescription-list">{template.exercises.map((item, index) => { const exercise = exercises.find((candidate) => candidate.id === item.exerciseId); return <article key={item.id}><ExerciseIllustration exercise={exercise} /><div className="prescription-copy"><strong>{exercise?.name ?? 'Exercício indisponível'}</strong><span>{exercise ? `${MUSCLE_LABELS[exercise.primaryMuscle]} · ${exercise.equipment.map((value) => EQUIPMENT_LABELS[value]).join(', ')}` : 'Revise esta referência'}</span><input aria-label={`Observação de ${exercise?.name}`} placeholder="Observação opcional" value={item.notes ?? ''} onChange={(event) => updateExercise(index, { notes: event.target.value || undefined })} /></div><label>Séries<input type="number" inputMode="numeric" min="1" max="10" value={item.workingSets} onChange={(event) => updateExercise(index, { workingSets: Number(event.target.value) })} /></label><label>Mín.<input type="number" inputMode="numeric" min="1" value={item.target.minimum} onChange={(event) => updateExercise(index, { target: { ...item.target, minimum: Number(event.target.value) } })} /></label><label>Máx.<input type="number" inputMode="numeric" min="1" value={item.target.maximum} onChange={(event) => updateExercise(index, { target: { ...item.target, maximum: Number(event.target.value) } })} /></label><label>Descanso<input type="number" inputMode="numeric" min="0" step="15" value={item.restSeconds} onChange={(event) => updateExercise(index, { restSeconds: Number(event.target.value) })} /></label><label>Carga inicial<input type="number" inputMode="decimal" min="0" step="0.5" value={item.targetLoad ?? ''} onChange={(event) => updateExercise(index, { targetLoad: event.target.value === '' ? undefined : Number(event.target.value) })} /></label><div className="prescription-actions"><button aria-label={`Mover ${exercise?.name} para cima`} disabled={index === 0} onClick={() => move(index, -1)}>↑</button><button aria-label={`Mover ${exercise?.name} para baixo`} disabled={index === template.exercises.length - 1} onClick={() => move(index, 1)}>↓</button><button aria-label={`Remover ${exercise?.name}`} onClick={() => updateTemplate({ exercises: template.exercises.filter((_, current) => current !== index).map((value, order) => ({ ...value, order })) })}>×</button></div></article>; })}</div>
      <footer><button className="training-secondary" onClick={() => setAdding(true)}>+ Adicionar exercício</button><button className="training-primary" disabled={busy} onClick={() => void save()}>{busy ? 'Salvando…' : 'Salvar nova versão'}</button></footer>
    </section>{adding && <ExercisePicker exercises={exercises} onPick={addExercise} onClose={() => setAdding(false)} />}
  </div>;
}

function ExerciseLibrary({ profileId, exercises, favorites, onChanged }: { profileId: string; exercises: Exercise[]; favorites: Set<string>; onChanged: (message: string) => void }) {
  const [query, setQuery] = useState(''); const [muscle, setMuscle] = useState<MuscleGroup | ''>(''); const [equipment, setEquipment] = useState<Equipment | ''>(''); const [onlyFavorites, setOnlyFavorites] = useState(false); const [onlyCustom, setOnlyCustom] = useState(false); const [customOpen, setCustomOpen] = useState(false); const [selected, setSelected] = useState<Exercise>();
  const results = useMemo(() => searchExercises(exercises, query, muscle || undefined, equipment || undefined).filter((item) => (!onlyFavorites || favorites.has(item.id)) && (!onlyCustom || item.isCustom)), [equipment, exercises, favorites, muscle, onlyCustom, onlyFavorites, query]);
  async function toggleFavorite(exerciseId: string) { if (favorites.has(exerciseId)) await repositories.exercises.removeFavorite(profileId, exerciseId); else { const timestamp = new Date().toISOString(); await repositories.exercises.saveFavorite({ id: createUuid(), profileId, exerciseId, createdAt: timestamp, updatedAt: timestamp }); } onChanged('Favoritos atualizados para este perfil.'); }
  return <div className="exercise-library"><div className="exercise-toolbar"><label>Buscar<input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Nome, músculo ou equipamento" /></label><DefynSelect label="Grupo muscular" value={muscle} onChange={(value) => setMuscle(value as MuscleGroup | '')} options={[{ value: '', label: 'Todos os músculos' }, ...(Object.keys(MUSCLE_LABELS) as MuscleGroup[]).map((value) => ({ value, label: MUSCLE_LABELS[value] }))]} /><DefynSelect label="Equipamento" value={equipment} onChange={(value) => setEquipment(value as Equipment | '')} options={[{ value: '', label: 'Todos os equipamentos' }, ...(Object.keys(EQUIPMENT_LABELS) as Equipment[]).map((value) => ({ value, label: EQUIPMENT_LABELS[value] }))]} /><button className={onlyFavorites ? 'active' : ''} onClick={() => setOnlyFavorites((value) => !value)}>☆ Favoritos</button><button className={onlyCustom ? 'active' : ''} onClick={() => setOnlyCustom((value) => !value)}>Meus exercícios</button><button className="training-primary" onClick={() => setCustomOpen(true)}>+ Exercício próprio</button></div>
    <div className="exercise-grid">{results.map((exercise) => <article key={exercise.id}><button className="exercise-open" onClick={() => setSelected(exercise)}><ExerciseIllustration exercise={exercise} /><span><strong>{exercise.name}</strong><small>{MUSCLE_LABELS[exercise.primaryMuscle]} · {exercise.equipment.map((item) => EQUIPMENT_LABELS[item]).join(', ')}</small></span></button><button className={favorites.has(exercise.id) ? 'favorite active' : 'favorite'} aria-label={`${favorites.has(exercise.id) ? 'Remover' : 'Adicionar'} ${exercise.name} dos favoritos`} onClick={() => void toggleFavorite(exercise.id)}>{favorites.has(exercise.id) ? '★' : '☆'}</button></article>)}</div>
    {selected && <ExerciseDetail profileId={profileId} exercise={selected} exercises={exercises} onClose={() => setSelected(undefined)} />}{customOpen && <CustomExercise profileId={profileId} onClose={() => setCustomOpen(false)} onSaved={() => { setCustomOpen(false); onChanged('Exercício próprio salvo para este perfil.'); }} />}
  </div>;
}

function ExercisePicker({ exercises, onPick, onClose }: { exercises: Exercise[]; onPick: (exercise: Exercise) => void; onClose: () => void }) { const [query, setQuery] = useState(''); const results = searchExercises(exercises, query).slice(0, 30); return <div className="training-modal-backdrop" onMouseDown={(event) => { if (event.target === event.currentTarget) onClose(); }}><section className="training-modal" role="dialog" aria-modal="true" aria-label="Adicionar exercício"><header><h2>Adicionar exercício</h2><button onClick={onClose}>×</button></header><input autoFocus value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Buscar por nome ou equipamento" /><div className="exercise-picker-list">{results.map((exercise) => <button key={exercise.id} onClick={() => onPick(exercise)}><ExerciseIllustration exercise={exercise} /><span><strong>{exercise.name}</strong><small>{MUSCLE_LABELS[exercise.primaryMuscle]}</small></span><b>+</b></button>)}</div></section></div>; }

function CustomExercise({ profileId, onClose, onSaved }: { profileId: string; onClose: () => void; onSaved: () => void }) { const [name, setName] = useState(''); const [muscle, setMuscle] = useState<MuscleGroup>('other'); const [equipment, setEquipment] = useState<Equipment>('other'); const [notes, setNotes] = useState(''); async function save(event: FormEvent) { event.preventDefault(); const timestamp = new Date().toISOString(); await repositories.exercises.saveCustom({ id: createUuid(), name: name.trim(), normalizedName: normalizeExerciseName(name), primaryMuscle: muscle, secondaryMuscles: [], equipment: [equipment], movementPattern: 'other', laterality: 'bilateral', instructions: ['Ajuste a posição com segurança.', 'Execute de forma controlada.', 'Retorne à posição inicial sem perder a postura.'], notes: notes.trim() || undefined, source: 'custom', isCustom: true, ownerProfileId: profileId, metric: 'reps', createdAt: timestamp, updatedAt: timestamp }); onSaved(); } return <div className="training-modal-backdrop"><section className="training-modal" role="dialog" aria-modal="true" aria-label="Novo exercício"><header><h2>Exercício próprio</h2><button onClick={onClose}>×</button></header><form className="custom-exercise-form" onSubmit={(event) => void save(event)}><label>Nome<input required value={name} onChange={(event) => setName(event.target.value)} /></label><label>Músculo<DefynSelect label="Músculo principal" value={muscle} onChange={(value) => setMuscle(value as MuscleGroup)} options={(Object.keys(MUSCLE_LABELS) as MuscleGroup[]).map((value) => ({ value, label: MUSCLE_LABELS[value] }))} /></label><label>Equipamento<DefynSelect label="Equipamento" value={equipment} onChange={(value) => setEquipment(value as Equipment)} options={(Object.keys(EQUIPMENT_LABELS) as Equipment[]).map((value) => ({ value, label: EQUIPMENT_LABELS[value] }))} /></label><label>Observação<textarea value={notes} onChange={(event) => setNotes(event.target.value)} /></label><button className="training-primary">Salvar exercício</button></form></section></div>; }

function ExerciseDetail({ profileId, exercise, exercises, onClose }: { profileId: string; exercise: Exercise; exercises: Exercise[]; onClose: () => void }) {
  const [history, setHistory] = useState<WorkoutSetLog[]>([]);
  useEffect(() => { let active = true; repositories.workoutSessions.listExerciseLogs(profileId, exercise.id).then((logs) => { if (active) setHistory(logs.filter((item) => item.completed).sort((a, b) => (b.completedAt ?? '').localeCompare(a.completedAt ?? '')).slice(0, 8)); }); return () => { active = false; }; }, [exercise.id, profileId]);
  const alternatives = exercises.filter((item) => item.id !== exercise.id && item.primaryMuscle === exercise.primaryMuscle && item.movementPattern === exercise.movementPattern).slice(0, 4);
  const kg = calculateExerciseRecords(history, 'kg'); const lb = calculateExerciseRecords(history, 'lb');
  return <div className="training-modal-backdrop" onMouseDown={(event) => { if (event.target === event.currentTarget) onClose(); }}><section className="training-modal exercise-detail" role="dialog" aria-modal="true" aria-label={exercise.name}><header><div><span className="page-eyebrow">{MUSCLE_LABELS[exercise.primaryMuscle]}</span><h2>{exercise.name}</h2></div><button onClick={onClose}>×</button></header><ExerciseIllustration exercise={exercise} large /><p>{exercise.equipment.map((item) => EQUIPMENT_LABELS[item]).join(' · ')}</p><ol>{exercise.instructions.map((instruction) => <li key={instruction}>{instruction}</li>)}</ol>{exercise.notes && <aside>{exercise.notes}</aside>}<section className="exercise-personal-history"><strong>Histórico pessoal</strong>{history.length > 0 && <small>Recordes reais: {[kg.maximumLoad !== undefined && `${kg.maximumLoad} kg`, lb.maximumLoad !== undefined && `${lb.maximumLoad} lb`].filter(Boolean).join(' · ') || 'carga não informada'} · sem estimativa de 1RM</small>}<p>{history.length ? history.map(formatSet).join(' · ') : 'Nenhum registro para este perfil.'}</p></section><section className="exercise-alternatives"><strong>Alternativas</strong><div className="exercise-alternative-list">{alternatives.length ? alternatives.map((item) => <span key={item.id}><ExerciseIllustration exercise={item} /><b>{item.name}</b></span>) : <p>Nenhuma alternativa equivalente no catálogo atual.</p>}</div></section></section></div>;
}

function TrainingHistory({ profileId, sessions, exercises }: { profileId: string; sessions: WorkoutSession[]; exercises: Exercise[] }) {
  const [selected, setSelected] = useState<WorkoutSession>();
  const [logs, setLogs] = useState<WorkoutSetLog[]>([]);
  const completed = sessions.filter((session) => session.status === 'completed');
  async function open(session: WorkoutSession) { setSelected(session); setLogs(await repositories.workoutSessions.listSetLogs(profileId, session.id)); }
  return <div className="training-history">
    {completed.length === 0 ? <div className="training-empty"><h2>O histórico começa no primeiro treino.</h2><p>Séries, cargas e exercícios concluídos aparecerão aqui sem dados inventados.</p></div> : <div className="history-list">{completed.map((session) => <button key={session.id} onClick={() => void open(session)}><time>{new Intl.DateTimeFormat('pt-BR', { day: '2-digit', month: 'short' }).format(new Date(`${session.localDate}T12:00:00`))}</time><span><strong>{session.templateName}</strong><small>{session.exercises.length} exercícios · {durationMinutes(session)} min</small></span><b>↗</b></button>)}</div>}
    {selected && <div className="training-modal-backdrop"><section className="training-modal history-detail"><header><div><span className="page-eyebrow">Sessão concluída · {new Intl.DateTimeFormat('pt-BR', { dateStyle: 'long', timeStyle: 'short' }).format(new Date(selected.completedAt ?? selected.startedAt))}</span><h2>{selected.templateName}</h2></div><button onClick={() => setSelected(undefined)}>×</button></header><div className="history-summary"><span>{durationMinutes(selected)} min</span><span>{logs.filter((log) => log.completed).length} séries</span><span>{Math.round(sessionVolume(logs.filter((log) => log.loadUnit === 'kg'))).toLocaleString('pt-BR')} kg de volume</span>{logs.some((log) => log.loadUnit === 'lb') && <span>{Math.round(sessionVolume(logs.filter((log) => log.loadUnit === 'lb'))).toLocaleString('pt-BR')} lb de volume</span>}</div>{selected.exercises.map((exercise) => { const exerciseLogs = logs.filter((log) => log.exerciseId === exercise.exerciseId && log.completed); const suggestion = exerciseLogs.length ? suggestDoubleProgression(exercise, exerciseLogs) : undefined; return <article key={exercise.prescriptionId} className={selected.skippedExerciseIds.includes(exercise.exerciseId) ? 'skipped' : ''}><ExerciseIllustration exercise={exercises.find((item) => item.id === exercise.exerciseId)} /><div><strong>{exercise.name}</strong><p>{exerciseLogs.length ? exerciseLogs.map(formatSet).join(' · ') : selected.skippedExerciseIds.includes(exercise.exerciseId) ? 'Pulado nesta sessão' : 'Sem séries concluídas'}</p>{suggestion && <small className={`progression-note ${suggestion.kind}`}>{suggestion.message}</small>}</div></article>; })}{selected.notes && <aside className="history-session-note"><strong>Nota da sessão</strong><p>{selected.notes}</p></aside>}</section></div>}
  </div>;
}


function durationMinutes(session: WorkoutSession): number { const end = session.completedAt ? new Date(session.completedAt).getTime() : Date.now(); return Math.max(1, Math.round((end - new Date(session.startedAt).getTime()) / 60000)); }
