import { useCallback, useEffect, useMemo, useRef, useState, type FormEvent } from 'react';
import { ProgressService, type ProgressOverview } from '../../application/progress/progress-service';
import { optimizeImage } from '../../application/media/image-processing';
import type { LocalMedia } from '../../domain/media/media';
import type { UserProfile } from '../../domain/profile/profile';
import { createProgressPeriod, MEASUREMENT_LABELS, normalizeDecimal, PROGRESS_PERIOD_LABELS, type BodyMeasurements, type ProgressPeriodPreset, type ProgressPhotoCategory, type ProgressPhotoMetadata, type ProgressRecord } from '../../domain/progress/progress';
import { toLocalDateKey } from '../../domain/shared/local-date';
import { repositories } from '../../infrastructure/repositories';
import { DefynSelect } from '../../shared/components/DefynSelect';
import { browserCapabilities } from '../../platform/device-capabilities';
import './progress-workspace.css';

const service = new ProgressService(repositories.progress, repositories.diary, repositories.nutritionTargets, repositories.water, repositories.workoutPlans, repositories.workoutSessions, repositories.media);
type ProgressTab = 'overview' | 'body' | 'photos' | 'nutrition' | 'training';
const tabs: { id: ProgressTab; label: string }[] = [{id:'overview',label:'Visão geral'},{id:'body',label:'Corpo'},{id:'photos',label:'Fotos'},{id:'nutrition',label:'Nutrição'},{id:'training',label:'Treinos'}];
const periodOptions = (Object.entries(PROGRESS_PERIOD_LABELS) as [ProgressPeriodPreset,string][]).map(([value,label])=>({value,label}));
const categoryLabels: Record<ProgressPhotoCategory,string> = {front:'Frente',side:'Lado',back:'Costas',free:'Livre'};

export function ProgressWorkspace({ profile, revision, onChanged, onNotice, onEditProfile }: { profile: UserProfile; revision: number; onChanged:()=>void; onNotice:(message:string)=>void; onEditProfile:()=>void }) {
  const [tab,setTab]=useState<ProgressTab>('overview'); const [preset,setPreset]=useState<ProgressPeriodPreset>('30d');
  const [data,setData]=useState<ProgressOverview>(); const [loading,setLoading]=useState(true); const [error,setError]=useState(''); const [localRevision,setLocalRevision]=useState(0);
  const [recordDialog,setRecordDialog]=useState<{mode:'weight'|'check-in';record?:ProgressRecord}>(); const [photoDialog,setPhotoDialog]=useState(false);
  const period=useMemo(()=>createProgressPeriod(preset),[preset]);
  const load=useCallback(async()=>{setLoading(true);try{setData(await service.overview(profile,period));setError('');}catch(caught){setError(caught instanceof Error?caught.message:'Não foi possível abrir o progresso.');}finally{setLoading(false);}},[profile,period]);
  useEffect(()=>{queueMicrotask(()=>void load());},[load,revision,localRevision]);
  async function changed(message:string){setLocalRevision((value)=>value+1);onChanged();onNotice(message);}
  async function removeRecord(record:ProgressRecord){if(!window.confirm(record.source==='check-in'?'Excluir este check-in e as fotos vinculadas?':'Excluir este registro corporal?'))return;if(record.source==='check-in')await service.removeCheckIn(profile.id,record.id);else await service.removeRecord(profile.id,record.id);await changed(record.source==='check-in'?'Check-in e mídias vinculadas excluídos.':'Registro corporal excluído.');}
  async function removePhoto(photo:ProgressPhotoMetadata){if(!window.confirm('Excluir esta foto local de progresso?'))return;await service.removePhoto(profile.id,photo.id);await changed('Foto de progresso excluída deste dispositivo.');}
  if(error&&!data)return <div className="page-state error-state" role="alert"><strong>Progresso indisponível.</strong><p>{error}</p><button onClick={()=>void load()}>Tentar novamente</button></div>;
  return <div className="progress-page page-container">
    <header className="progress-header"><div><span className="page-eyebrow">Histórico local e explicável</span><h1>Progresso</h1><p>Tendências de {profile.name} sem notas morais, diagnósticos ou metas alteradas automaticamente.</p></div><div className="progress-header-actions"><button className="progress-primary" onClick={()=>setRecordDialog({mode:'check-in'})}>+ Fazer check-in</button><DefynSelect value={preset} options={periodOptions} onChange={setPreset} label="Período do progresso" /></div></header>
    <nav className="progress-tabs" aria-label="Áreas do progresso">{tabs.map((item)=><button key={item.id} className={tab===item.id?'active':''} aria-current={tab===item.id?'page':undefined} onClick={()=>setTab(item.id)}>{item.label}</button>)}</nav>
    {loading&&!data?<ProgressSkeleton/>:data&&<>
      {tab==='overview'&&<Overview data={data} profile={profile} onAddWeight={()=>setRecordDialog({mode:'weight'})} onCheckIn={()=>setRecordDialog({mode:'check-in'})} onAddPhoto={()=>setPhotoDialog(true)} onTab={setTab}/>} 
      {tab==='body'&&<BodyPanel data={data} profile={profile} onAdd={()=>setRecordDialog({mode:'weight'})} onEdit={(record)=>setRecordDialog({mode:record.source==='check-in'?'check-in':'weight',record})} onRemove={(record)=>void removeRecord(record)} onEditProfile={onEditProfile}/>} 
      {tab==='photos'&&<PhotosPanel photos={data.photos} onAdd={()=>setPhotoDialog(true)} onRemove={(photo)=>void removePhoto(photo)}/>} 
      {tab==='nutrition'&&<NutritionPanel data={data}/>} 
      {tab==='training'&&<TrainingPanel data={data}/>} 
    </>}
    {error&&<p className="progress-inline-error" role="alert">{error}</p>}
    {recordDialog&&<RecordDialog profileId={profile.id} mode={recordDialog.mode} record={recordDialog.record} onClose={()=>setRecordDialog(undefined)} onSaved={async(message)=>{setRecordDialog(undefined);await changed(message);}}/>}
    {photoDialog&&<PhotoDialog profileId={profile.id} onClose={()=>setPhotoDialog(false)} onSaved={async()=>{setPhotoDialog(false);await changed('Foto otimizada e salva somente neste dispositivo.');}}/>}
  </div>;
}

function Overview({data,profile,onAddWeight,onCheckIn,onAddPhoto,onTab}:{data:ProgressOverview;profile:UserProfile;onAddWeight:()=>void;onCheckIn:()=>void;onAddPhoto:()=>void;onTab:(tab:ProgressTab)=>void}){
  const latest=[...data.records].filter((r)=>r.weightKg!==undefined).sort((a,b)=>b.localDate.localeCompare(a.localDate))[0];
  return <section className="progress-overview"><div className="progress-kpis">
    <SummaryCard tone="dark" eyebrow="Peso mais recente" value={latest?`${formatNumber(latest.weightKg!)} kg`:'Sem registro'} detail={latest?formatDate(latest.localDate):'Registre quando fizer sentido'} onClick={onAddWeight}/>
    <SummaryCard tone="body" eyebrow="Tendência de 7 dias" value={data.trend.changeKg===undefined?'Coletando dados':`${data.trend.changeKg>0?'+':''}${formatNumber(data.trend.changeKg)} kg`} detail={data.trend.message} onClick={()=>onTab('body')}/>
    <SummaryCard tone="nutrition" eyebrow="Diário registrado" value={`${data.nutrition.registeredDays} dia(s)`} detail={data.nutrition.averageCalories===undefined?'Dias sem diário não contam como zero':`${Math.round(data.nutrition.averageCalories).toLocaleString('pt-BR')} kcal em média`} onClick={()=>onTab('nutrition')}/>
    <SummaryCard tone="training" eyebrow="Treinos concluídos" value={`${data.training.completedSessions}`} detail={data.training.adherence===undefined?'Sem agenda comparável':`${data.training.adherence}% do planejado`} onClick={()=>onTab('training')}/>
  </div>
  <div className="progress-overview-grid"><article className="progress-panel weight-feature"><PanelHead eyebrow="Evolução corporal" title="Peso no período" action={<button onClick={onAddWeight}>Registrar peso</button>}/><WeightChart records={data.records} target={profile.targetWeightKg}/></article>
  <article className="progress-panel insights-panel"><PanelHead eyebrow="Leitura determinística" title="Pontos do período"/><ul>{data.insights.length?data.insights.map((item)=><li key={item}>{item}</li>):<li>Registre alguns dias para o DEFYN resumir o período sem inventar conclusões.</li>}</ul></article></div>
  <div className="progress-quick-actions"><button onClick={onCheckIn}><span>01</span><strong>Check-in completo</strong><small>Peso, medidas, fotos e nota — tudo opcional.</small></button><button onClick={onAddPhoto}><span>02</span><strong>Adicionar foto</strong><small>Frente, lado, costas ou livre.</small></button><button onClick={()=>onTab('training')}><span>03</span><strong>Ver consistência</strong><small>Frequência, duração, séries e volume válido.</small></button></div>
  </section>;
}

function BodyPanel({data,profile,onAdd,onEdit,onRemove,onEditProfile}:{data:ProgressOverview;profile:UserProfile;onAdd:()=>void;onEdit:(record:ProgressRecord)=>void;onRemove:(record:ProgressRecord)=>void;onEditProfile:()=>void}){
  const records=[...data.records].sort((a,b)=>b.occurredAt.localeCompare(a.occurredAt)); const latest=records.find((r)=>r.weightKg!==undefined);
  return <section className="body-panel"><div className="body-hero progress-panel"><div><span className="page-eyebrow">Corpo</span><h2>{latest?`${formatNumber(latest.weightKg!)} kg`:'Seu ponto de partida'}</h2><p>{profile.targetWeightKg?`Meta informada: ${formatNumber(profile.targetWeightKg)} kg. O histórico não altera sua ficha automaticamente.`:'Nenhum peso-alvo informado. O histórico continua útil sem ele.'}</p></div><button className="progress-primary" onClick={onAdd}>+ Registrar peso</button></div>
  <div className="body-grid"><article className="progress-panel"><PanelHead eyebrow="Tendência" title="Médias de 7 dias"/><WeightChart records={data.records} target={profile.targetWeightKg}/><button className="text-action" onClick={onEditProfile}>Revisar ficha e metas →</button></article><article className="progress-panel measurement-latest"><PanelHead eyebrow="Último check-in" title="Medidas recentes"/>{latestMeasurements(records)}</article></div>
  <article className="progress-panel history-table"><PanelHead eyebrow="Histórico" title={`${records.length} registro(s)`}/>{records.length===0?<EmptyCopy title="Nenhum registro corporal" text="Registre apenas o que você deseja acompanhar."/>:<div className="history-scroll"><table><thead><tr><th>Data</th><th>Peso</th><th>Medidas</th><th>Origem</th><th><span className="sr-only">Ações</span></th></tr></thead><tbody>{records.map((record)=><tr key={record.id}><td>{formatDate(record.localDate)}</td><td>{record.weightKg?`${formatNumber(record.weightKg)} kg`:'—'}</td><td>{measurementSummary(record.measurements)}</td><td>{record.source==='check-in'?'Check-in':'Manual'}</td><td><button onClick={()=>onEdit(record)}>Editar</button><button className="danger-link" onClick={()=>onRemove(record)}>Excluir</button></td></tr>)}</tbody></table></div>}</article></section>;
}

function PhotosPanel({photos,onAdd,onRemove}:{photos:ProgressPhotoMetadata[];onAdd:()=>void;onRemove:(photo:ProgressPhotoMetadata)=>void}){
  const [category,setCategory]=useState<ProgressPhotoCategory>('front'); const filtered=useMemo(()=>[...photos].filter((p)=>p.category===category).sort((a,b)=>a.localDate.localeCompare(b.localDate)),[photos,category]); const [before,setBefore]=useState(''); const [after,setAfter]=useState('');
  const beforePhoto=filtered.find((p)=>p.id===before)??filtered[0]; const afterPhoto=filtered.find((p)=>p.id===after)??filtered.at(-1); const beforeId=beforePhoto?.id??''; const afterId=afterPhoto?.id??'';
  return <section className="photos-panel"><div className="photos-toolbar"><div><span className="page-eyebrow">Registro visual local</span><h2>Fotos de progresso</h2><p>Sem análise corporal por IA. Você escolhe o que comparar.</p></div><button className="progress-primary" onClick={onAdd}>+ Adicionar foto</button></div>
  <div className="category-tabs" role="group" aria-label="Categoria da foto">{Object.entries(categoryLabels).map(([id,label])=><button key={id} className={category===id?'active':''} onClick={()=>setCategory(id as ProgressPhotoCategory)}>{label}</button>)}</div>
  {filtered.length===0?<EmptyCopy title={`Nenhuma foto de ${categoryLabels[category].toLowerCase()}`} text="Fotos ficam apenas neste dispositivo e entram no backup local quando você exportar."/>:<>
    <article className="progress-panel compare-panel"><PanelHead eyebrow="Comparação" title="Antes e depois"/><div className="compare-selects"><label>Antes<select value={beforeId} onChange={(e)=>setBefore(e.target.value)}>{filtered.map((p)=><option key={p.id} value={p.id}>{formatDate(p.localDate)}</option>)}</select></label><label>Depois<select value={afterId} onChange={(e)=>setAfter(e.target.value)}>{filtered.map((p)=><option key={p.id} value={p.id}>{formatDate(p.localDate)}</option>)}</select></label></div><div className="compare-images"><PhotoFrame photo={beforePhoto} label="Antes"/><PhotoFrame photo={afterPhoto} label="Depois"/></div></article>
    <div className="photo-grid">{[...filtered].reverse().map((photo)=><article key={photo.id}><PhotoFrame photo={photo}/><footer><div><strong>{categoryLabels[photo.category]}</strong><small>{formatDate(photo.localDate)}</small></div><button className="danger-link" onClick={()=>onRemove(photo)}>Excluir</button></footer></article>)}</div>
  </>}</section>;
}

function NutritionPanel({data}:{data:ProgressOverview}){const n=data.nutrition,h=data.hydration;return <section className="analytics-section"><div className="analytics-grid"><article className="progress-panel nutrition-card"><PanelHead eyebrow="Nutrição" title="Média dos dias registrados"/><MetricRow color="protein" label="Proteína" value={n.proteinAverage===undefined?'Sem dados':`${Math.round(n.proteinAverage)} g`} detail={n.proteinTargetAverage===undefined?'Meta histórica indisponível':`meta média ${Math.round(n.proteinTargetAverage)} g`}/><MetricRow color="carbs" label="Carboidratos" value={n.carbsAverage===undefined?'Sem dados':`${Math.round(n.carbsAverage)} g`}/><MetricRow color="fat" label="Gorduras" value={n.fatAverage===undefined?'Sem dados':`${Math.round(n.fatAverage)} g`}/></article><article className="progress-panel calorie-analysis"><PanelHead eyebrow="Energia" title="Consumido × meta histórica"/><BigMetric value={n.averageCalories===undefined?'—':Math.round(n.averageCalories).toLocaleString('pt-BR')} unit="kcal / dia registrado"/><p>{n.registeredDays?`${n.registeredDays} dia(s) com diário. Diferença média: ${signed(n.averageDifference,'kcal')}.`:'Dias sem diário permanecem sem dado; não entram como zero.'}</p></article></div>
  <div className="analytics-grid"><article className="progress-panel hydration-analysis"><PanelHead eyebrow="Hidratação" title="Água nos dias registrados"/><BigMetric value={h.averageMl===undefined?'—':formatNumber(h.averageMl/1000)} unit="L em média"/><div className="water-stat"><span style={{width:`${Math.min(100,h.averageMl&&h.averageTargetMl?h.averageMl/h.averageTargetMl*100:0)}%`}}/></div><p>{h.registeredDays?`${h.daysAtTarget} de ${h.registeredDays} dia(s) registrados atingiram a meta daquele dia.`:'Registre água para formar o histórico.'}</p></article><article className="progress-panel"><PanelHead eyebrow="Como ler" title="Sem punição por silêncio"/><p className="explain-copy">Um dia sem diário ou água não é tratado como consumo zero. As médias usam somente dias com pelo menos um registro e respeitam a meta nutricional histórica ativa em cada data.</p></article></div></section>}

function TrainingPanel({data}:{data:ProgressOverview}){const t=data.training;const max=Math.max(1,...t.weekly.map((w)=>w.count));return <section className="analytics-section"><div className="training-kpis">
  <SummaryCard tone="training" eyebrow="Concluídos" value={`${t.completedSessions}`} detail={`${t.plannedSessions} planejado(s)`}/>
  <SummaryCard tone="body" eyebrow="Tempo total" value={`${t.totalMinutes} min`} detail={t.averageMinutes===undefined?'Sem sessões concluídas':`${Math.round(t.averageMinutes)} min em média`}/>
  <SummaryCard tone="nutrition" eyebrow="Séries válidas" value={`${t.completedSets}`} detail="Apenas séries concluídas"/>
  <SummaryCard tone="dark" eyebrow="Volume convencional" value={t.volumeKg?`${Math.round(t.volumeKg).toLocaleString('pt-BR')} kg`:'—'} detail={t.volumeLb?`Também ${Math.round(t.volumeLb).toLocaleString('pt-BR')} lb`:'Kg e lb não são misturados'}/>
  </div>
  <article className="progress-panel weekly-chart"><PanelHead eyebrow="Consistência" title="Treinos por semana"/>{t.weekly.length?<><div className="bars" role="img" aria-label={t.weekly.map((w)=>`${formatDate(w.label)}: ${w.count} treino(s)`).join('; ')}>{t.weekly.map((w)=><div key={w.label}><span style={{height:`${Math.max(8,w.count/max*100)}%`}} tabIndex={0} title={`${w.count} treino(s)`}/><small>{formatShortDate(w.label)}</small></div>)}</div><ul className="sr-only">{t.weekly.map((w)=><li key={w.label}>Semana de {formatDate(w.label)}: {w.count} treino(s)</li>)}</ul></>:<EmptyCopy title="Sem treinos concluídos" text="Sessões planejadas não contam como concluídas."/>}</article>
  <article className="progress-panel exercise-records"><PanelHead eyebrow="Exercícios" title="Melhores registros do período"/>{t.exerciseRecords.length?<div>{t.exerciseRecords.map((e)=><article key={e.exerciseId}><span>{e.name.slice(0,2).toUpperCase()}</span><div><strong>{e.name}</strong><small>{e.points.length} série(s) no histórico</small></div><b>{e.bestLoad!==undefined?`${formatNumber(e.bestLoad)} ${e.loadUnit}`:e.bestReps?`${e.bestReps} rep.`:'Registrado'}</b></article>)}</div>:<p className="explain-copy">Conclua séries para acompanhar carga, repetições e volume por exercício.</p>}</article></section>}

function RecordDialog({profileId,mode,record,onClose,onSaved}:{profileId:string;mode:'weight'|'check-in';record?:ProgressRecord;onClose:()=>void;onSaved:(message:string)=>void}){const capabilities=useMemo(()=>browserCapabilities(),[]);const photoGallery=useRef<HTMLInputElement>(null);const photoCamera=useRef<HTMLInputElement>(null);const [date,setDate]=useState(record?.localDate??toLocalDateKey(new Date()));const [weight,setWeight]=useState(record?.weightKg?.toString().replace('.',',')??'');const [note,setNote]=useState(record?.note??'');const [measurements,setMeasurements]=useState<Record<string,string>>(()=>Object.fromEntries(Object.entries(record?.measurements??{}).filter(([,v])=>typeof v==='number').map(([k,v])=>[k,String(v).replace('.',',')])));const [photo,setPhoto]=useState<File>();const [photoCategory,setPhotoCategory]=useState<ProgressPhotoCategory>('front');const [busy,setBusy]=useState(false);const [error,setError]=useState('');
  const keys=mode==='check-in'?['waistCm','abdomenCm','chestCm','hipCm','leftArmCm','rightArmCm','leftThighCm','rightThighCm','bodyFatPercent']:[];
  async function submit(event:FormEvent){event.preventDefault();setBusy(true);setError('');try{const body=Object.fromEntries(Object.entries(measurements).filter(([,v])=>v.trim()).map(([k,v])=>[k,normalizeDecimal(v)])) as BodyMeasurements;if(mode==='check-in'&&!record&&!weight.trim()&&!Object.keys(body).length&&!note.trim()&&!photo)throw new Error('Inclua ao menos peso, medida, foto ou observação.');const saved=await service.saveRecord(profileId,{id:record?.id,localDate:date,weightKg:weight.trim()?normalizeDecimal(weight):undefined,measurements:Object.keys(body).length?body:undefined,note,source:mode==='check-in'?'check-in':'manual'});if(photo){const photoId=crypto.randomUUID();const media=await optimizeImage(photo,'progress-photo','progress',photoId);await service.savePhoto(profileId,saved.id,date,photoCategory,media);}onSaved(record?'Registro corporal atualizado.':mode==='check-in'?'Check-in salvo neste dispositivo.':'Peso registrado sem alterar suas metas.');}catch(caught){setError(caught instanceof Error?caught.message:'Não foi possível salvar.');}finally{setBusy(false);}}
  return <div className="progress-modal-backdrop"><form className="progress-modal" role="dialog" aria-modal="true" aria-label={mode==='check-in'?'Check-in corporal':'Registrar peso'} onSubmit={submit}><header><div><span className="page-eyebrow">{record?'Editar registro':'Novo registro'}</span><h2>{mode==='check-in'?'Check-in corporal':'Registrar peso'}</h2></div><button type="button" onClick={onClose} aria-label="Fechar">×</button></header><div className="record-fields"><label>Data<input type="date" required value={date} max={toLocalDateKey(new Date())} onChange={(e)=>setDate(e.target.value)}/></label><label>Peso em kg <small>opcional no check-in</small><input inputMode="decimal" placeholder="Ex.: 78,4" value={weight} onChange={(e)=>setWeight(e.target.value)}/></label>{keys.map((key)=><label key={key}>{MEASUREMENT_LABELS[key]} {key==='bodyFatPercent'?'(%)':'(cm)'}<input inputMode="decimal" value={measurements[key]??''} onChange={(e)=>setMeasurements((current)=>({...current,[key]:e.target.value}))}/></label>)}</div>{mode==='check-in'&&<div className="checkin-photo"><div className="photo-source-buttons"><button type="button" onClick={()=>photoGallery.current?.click()}>Escolher da galeria</button>{capabilities.camera&&<button type="button" onClick={()=>photoCamera.current?.click()}>Tirar foto</button>}</div><input ref={photoGallery} className="sr-only" type="file" accept="image/jpeg,image/png,image/webp" onChange={(e)=>setPhoto(e.target.files?.[0])}/><input ref={photoCamera} className="sr-only" type="file" accept="image/*" capture="environment" onChange={(e)=>setPhoto(e.target.files?.[0])}/><label>Categoria<select value={photoCategory} onChange={(e)=>setPhotoCategory(e.target.value as ProgressPhotoCategory)}>{Object.entries(categoryLabels).map(([id,label])=><option key={id} value={id}>{label}</option>)}</select></label>{photo&&<p className="selected-file"><strong>{photo.name}</strong><span>Foto pronta para o check-in</span></p>}</div>}<label className="note-field">Observação opcional<textarea value={note} maxLength={500} onChange={(e)=>setNote(e.target.value)} placeholder="Contexto que você quer lembrar, sem julgamento."/></label><p className="responsibility-note">Registrar peso não recalcula calorias, macros ou hidratação automaticamente.</p>{error&&<p className="progress-form-error" role="alert">{error}</p>}<footer><button type="button" onClick={onClose}>Cancelar</button><button className="progress-primary" disabled={busy}>{busy?'Salvando…':'Salvar registro'}</button></footer></form></div>;
}

function PhotoDialog({profileId,onClose,onSaved}:{profileId:string;onClose:()=>void;onSaved:()=>void}){const capabilities=useMemo(()=>browserCapabilities(),[]);const [date,setDate]=useState(toLocalDateKey(new Date()));const [category,setCategory]=useState<ProgressPhotoCategory>('front');const [file,setFile]=useState<File>();const preview=useMemo(()=>file?URL.createObjectURL(file):'',[file]);const [busy,setBusy]=useState(false);const [error,setError]=useState('');const gallery=useRef<HTMLInputElement>(null);const camera=useRef<HTMLInputElement>(null);
  async function submit(event:FormEvent){event.preventDefault();if(!file){setError('Escolha uma imagem.');return;}setBusy(true);setError('');try{const photoId=crypto.randomUUID();const media=await optimizeImage(file,'progress-photo','progress',photoId);await service.savePhoto(profileId,undefined,date,category,media);onSaved();}catch(caught){setError(caught instanceof Error?caught.message:'Não foi possível salvar a foto.');}finally{setBusy(false);}}
  useEffect(()=>()=>{if(preview)URL.revokeObjectURL(preview);},[preview]);
  const select=(event:React.ChangeEvent<HTMLInputElement>)=>setFile(event.target.files?.[0]);
  const guidance=category==='front'?'Corpo de frente, câmera na altura do tronco.':category==='side'?'Perfil lateral, mantendo a mesma distância.':category==='back'?'Corpo de costas, com enquadramento semelhante.':'Use o enquadramento que fizer sentido para você.';
  return <div className="progress-modal-backdrop"><form className="progress-modal photo-form" role="dialog" aria-modal="true" aria-label="Adicionar foto de progresso" onSubmit={submit}><header><div><span className="page-eyebrow">Arquivo local otimizado</span><h2>Adicionar foto</h2></div><button type="button" onClick={onClose} aria-label="Fechar">×</button></header><div className="record-fields"><label>Data<input type="date" required value={date} max={toLocalDateKey(new Date())} onChange={(e)=>setDate(e.target.value)}/></label><label>Categoria<select value={category} onChange={(e)=>setCategory(e.target.value as ProgressPhotoCategory)}>{Object.entries(categoryLabels).map(([id,label])=><option key={id} value={id} label={label}>{label}</option>)}</select></label></div><p className="photo-guidance">{guidance} A foto é opcional e nunca é analisada por IA.</p><div className="photo-source-buttons"><button type="button" onClick={()=>gallery.current?.click()}>Escolher da galeria</button>{capabilities.camera&&<button type="button" onClick={()=>camera.current?.click()}>Tirar foto</button>}</div><input ref={gallery} className="sr-only" type="file" accept="image/jpeg,image/png,image/webp" onChange={select}/><input ref={camera} className="sr-only" type="file" accept="image/*" capture="environment" onChange={select}/>{preview&&<img className="progress-photo-preview" src={preview} alt={`Prévia da foto: ${categoryLabels[category]}`}/>} {file&&<p className="selected-file"><strong>{file.name}</strong><span>{(file.size/1024/1024).toFixed(1)} MB antes da otimização</span></p>}<p className="responsibility-note">A imagem é orientada, reduzida e comprimida no navegador. Nenhum upload externo é feito.</p>{error&&<p className="progress-form-error" role="alert">{error}</p>}<footer><button type="button" onClick={onClose}>Cancelar</button><button className="progress-primary" disabled={busy}>{busy?'Otimizando…':'Salvar foto'}</button></footer></form></div>;
}

function WeightChart({records,target}:{records:ProgressRecord[];target?:number}){const points=[...records].filter((r):r is ProgressRecord&{weightKg:number}=>r.weightKg!==undefined).sort((a,b)=>a.localDate.localeCompare(b.localDate));if(!points.length)return <EmptyCopy title="Sem curva ainda" text="O gráfico aparece após o primeiro peso, e a tendência exige mais registros."/>;const values=points.map((p)=>p.weightKg);if(target)values.push(target);const min=Math.min(...values)-1,max=Math.max(...values)+1,range=Math.max(1,max-min);const xy=points.map((p,i)=>({x:points.length===1?50:6+i/(points.length-1)*88,y:92-(p.weightKg-min)/range*78,p}));const path=xy.map((p,i)=>`${i?'L':'M'} ${p.x} ${p.y}`).join(' ');const targetY=target===undefined?undefined:92-(target-min)/range*78;return <div className="weight-chart"><svg viewBox="0 0 100 100" role="img" aria-label={points.map(({localDate,weightKg})=>`${formatDate(localDate)}: ${formatNumber(weightKg!)} kg`).join('; ')} preserveAspectRatio="none"><defs><linearGradient id="weight-fill" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="#4f84aa" stopOpacity=".24"/><stop offset="1" stopColor="#4f84aa" stopOpacity="0"/></linearGradient></defs>{targetY!==undefined&&<line className="target-line" x1="4" x2="96" y1={targetY} y2={targetY}/>}<path className="weight-area" d={`${path} L ${xy.at(-1)?.x} 96 L ${xy[0]?.x} 96 Z`}/><path className="weight-line" d={path}/>{xy.map(({x,y,p})=><circle key={p.id} cx={x} cy={y} r="1.7" tabIndex={0}><title>{formatDate(p.localDate)} · {formatNumber(p.weightKg)} kg</title></circle>)}</svg><div><span>{formatNumber(max-1)} kg</span>{target!==undefined&&<span className="target-label">Meta {formatNumber(target)} kg</span>}<span>{formatNumber(min+1)} kg</span></div><ul className="chart-text">{points.slice(-8).map((p)=><li key={p.id}><time>{formatDate(p.localDate)}</time><strong>{formatNumber(p.weightKg)} kg</strong></li>)}</ul></div>}
function PhotoFrame({photo,label}:{photo?:ProgressPhotoMetadata;label?:string}){const [media,setMedia]=useState<LocalMedia>();const [url,setUrl]=useState('');useEffect(()=>{let active=true;let objectUrl='';if(!photo?.mediaId){queueMicrotask(()=>{if(active){setMedia(undefined);setUrl('');}});return()=>{active=false;};}repositories.media.getById(photo.mediaId).then((value)=>{if(!active||!value)return;objectUrl=URL.createObjectURL(value.blob);setMedia(value);setUrl(objectUrl);});return()=>{active=false;if(objectUrl)URL.revokeObjectURL(objectUrl);};},[photo?.mediaId]);return <figure className="photo-frame">{label&&<figcaption>{label}</figcaption>}{url?<img src={url} alt={`${categoryLabels[photo!.category]} em ${formatDate(photo!.localDate)}`} loading="lazy" decoding="async" width={media?.width} height={media?.height}/>:<div><span>Sem imagem</span><small>{photo?.mediaId?'Arquivo local indisponível':'Escolha uma data'}</small></div>}</figure>}
function SummaryCard({tone,eyebrow,value,detail,onClick}:{tone:string;eyebrow:string;value:string;detail:string;onClick?:()=>void}){const Tag=onClick?'button':'article';return <Tag className={`summary-card ${tone}`} onClick={onClick}><span>{eyebrow}</span><strong>{value}</strong><small>{detail}</small></Tag>}
function PanelHead({eyebrow,title,action}:{eyebrow:string;title:string;action?:React.ReactNode}){return <header className="panel-head"><div><span>{eyebrow}</span><h2>{title}</h2></div>{action}</header>}
function BigMetric({value,unit}:{value:string;unit:string}){return <div className="big-metric"><strong>{value}</strong><span>{unit}</span></div>}
function MetricRow({color,label,value,detail}:{color:string;label:string;value:string;detail?:string}){return <div className="metric-row"><i className={color}/><span><strong>{label}</strong>{detail&&<small>{detail}</small>}</span><b>{value}</b></div>}
function EmptyCopy({title,text}:{title:string;text:string}){return <div className="progress-empty"><span>↗</span><strong>{title}</strong><p>{text}</p></div>}
function ProgressSkeleton(){return <div className="progress-skeleton" aria-label="Carregando progresso"><span/><span/><span/><span/></div>}
function measurementSummary(measurements?:BodyMeasurements){if(!measurements)return '—';const values=Object.entries(measurements).filter(([,v])=>typeof v==='number');return values.length?`${values.length} medida(s)`:'—'}
function latestMeasurements(records:ProgressRecord[]){const record=records.find((r)=>r.measurements&&Object.values(r.measurements).some((v)=>typeof v==='number'));if(!record)return <EmptyCopy title="Sem medidas" text="Medidas são opcionais e podem ser parciais."/>;return <dl>{Object.entries(record.measurements??{}).filter(([,v])=>typeof v==='number').slice(0,8).map(([key,value])=><div key={key}><dt>{MEASUREMENT_LABELS[key]??key}</dt><dd>{formatNumber(value as number)} {key==='bodyFatPercent'?'%':'cm'}</dd></div>)}</dl>}
function formatNumber(value:number){return value.toLocaleString('pt-BR',{maximumFractionDigits:1})}function formatDate(date:string){return new Intl.DateTimeFormat('pt-BR',{day:'2-digit',month:'short',year:'numeric'}).format(new Date(`${date}T12:00:00`))}function formatShortDate(date:string){return new Intl.DateTimeFormat('pt-BR',{day:'2-digit',month:'short'}).format(new Date(`${date}T12:00:00`))}function signed(value:number|undefined,unit:string){if(value===undefined)return 'indisponível';return `${value>0?'+':''}${Math.round(value).toLocaleString('pt-BR')} ${unit}`}
