import type { Equipment, MovementPattern, MuscleGroup } from './training';

export type ExerciseSeed = readonly [
  name: string,
  muscle: MuscleGroup,
  equipment: readonly Equipment[],
  pattern: MovementPattern,
  secondary?: readonly MuscleGroup[],
];

/**
 * Expanded catalog kept separate from the original 52 rows so their persisted IDs
 * remain stable. Names intentionally include the implement or setup: each variation
 * is independently selectable and keeps its own workout history.
 */
export const EXTENDED_EXERCISE_ROWS: readonly ExerciseSeed[] = [
  // Peitoral
  ['Supino inclinado com barra', 'chest', ['barbell', 'bench'], 'horizontal-push', ['front-delts', 'triceps']],
  ['Supino declinado com barra', 'chest', ['barbell', 'bench'], 'horizontal-push', ['triceps', 'front-delts']],
  ['Supino declinado com halteres', 'chest', ['dumbbell', 'bench'], 'horizontal-push', ['triceps', 'front-delts']],
  ['Supino reto na máquina', 'chest', ['machine'], 'horizontal-push', ['triceps', 'front-delts']],
  ['Supino inclinado na máquina', 'chest', ['machine'], 'horizontal-push', ['front-delts', 'triceps']],
  ['Supino reto no Smith', 'chest', ['smith', 'bench'], 'horizontal-push', ['triceps', 'front-delts']],
  ['Supino inclinado no Smith', 'chest', ['smith', 'bench'], 'horizontal-push', ['front-delts', 'triceps']],
  ['Supino com pegada fechada', 'triceps', ['barbell', 'bench'], 'horizontal-push', ['chest', 'front-delts']],
  ['Supino unilateral com halter', 'chest', ['dumbbell', 'bench'], 'horizontal-push', ['triceps', 'core']],
  ['Supino no chão com barra', 'chest', ['barbell'], 'horizontal-push', ['triceps']],
  ['Supino no chão com halteres', 'chest', ['dumbbell'], 'horizontal-push', ['triceps']],
  ['Crucifixo inclinado com halteres', 'chest', ['dumbbell', 'bench'], 'isolation', ['front-delts']],
  ['Crucifixo declinado com halteres', 'chest', ['dumbbell', 'bench'], 'isolation'],
  ['Crucifixo na máquina', 'chest', ['machine'], 'isolation', ['front-delts']],
  ['Crossover na polia alta', 'chest', ['cable'], 'isolation'],
  ['Crossover na polia baixa', 'chest', ['cable'], 'isolation', ['front-delts']],
  ['Crucifixo unilateral na polia', 'chest', ['cable'], 'isolation', ['core']],
  ['Flexão inclinada', 'chest', ['bodyweight', 'bench'], 'horizontal-push', ['triceps']],
  ['Flexão declinada', 'chest', ['bodyweight', 'bench'], 'horizontal-push', ['front-delts', 'triceps']],
  ['Flexão diamante', 'triceps', ['bodyweight'], 'horizontal-push', ['chest']],
  ['Flexão aberta', 'chest', ['bodyweight'], 'horizontal-push', ['front-delts']],
  ['Flexão com elástico', 'chest', ['bodyweight', 'band'], 'horizontal-push', ['triceps']],
  ['Flexão nas argolas', 'chest', ['rings', 'bodyweight'], 'horizontal-push', ['triceps', 'core']],
  ['Mergulho nas paralelas para peitoral', 'chest', ['bodyweight'], 'vertical-push', ['triceps', 'front-delts']],
  ['Pullover com halter', 'lats', ['dumbbell', 'bench'], 'isolation', ['chest']],
  ['Pullover na máquina', 'lats', ['machine'], 'isolation', ['chest']],

  // Costas, dorsais e lombar
  ['Puxada frontal pegada aberta', 'lats', ['cable'], 'vertical-pull', ['back', 'biceps']],
  ['Puxada frontal pegada fechada', 'lats', ['cable'], 'vertical-pull', ['back', 'biceps']],
  ['Puxada frontal pegada neutra', 'lats', ['cable'], 'vertical-pull', ['back', 'biceps']],
  ['Puxada frontal supinada', 'lats', ['cable'], 'vertical-pull', ['biceps', 'back']],
  ['Puxada unilateral na polia alta', 'lats', ['cable'], 'vertical-pull', ['biceps']],
  ['Puxada convergente na máquina', 'lats', ['machine'], 'vertical-pull', ['back', 'biceps']],
  ['Barra fixa pronada', 'lats', ['bodyweight'], 'vertical-pull', ['back', 'biceps']],
  ['Barra fixa supinada', 'biceps', ['bodyweight'], 'vertical-pull', ['lats', 'back']],
  ['Barra fixa pegada neutra', 'lats', ['bodyweight'], 'vertical-pull', ['biceps', 'back']],
  ['Barra fixa assistida na máquina', 'lats', ['machine'], 'vertical-pull', ['biceps', 'back']],
  ['Barra fixa com elástico', 'lats', ['bodyweight', 'band'], 'vertical-pull', ['biceps', 'back']],
  ['Remada baixa pegada neutra', 'back', ['cable'], 'horizontal-pull', ['lats', 'biceps']],
  ['Remada baixa pegada aberta', 'back', ['cable'], 'horizontal-pull', ['rear-delts', 'biceps']],
  ['Remada baixa unilateral', 'back', ['cable'], 'horizontal-pull', ['lats', 'biceps']],
  ['Remada cavalinho com barra T', 'back', ['barbell'], 'horizontal-pull', ['lats', 'biceps']],
  ['Remada cavalinho na máquina', 'back', ['machine'], 'horizontal-pull', ['lats', 'biceps']],
  ['Remada curvada com halteres', 'back', ['dumbbell'], 'horizontal-pull', ['lats', 'biceps']],
  ['Remada curvada com barra supinada', 'back', ['barbell'], 'horizontal-pull', ['lats', 'biceps']],
  ['Remada Pendlay', 'back', ['barbell'], 'horizontal-pull', ['lats', 'lower-back']],
  ['Remada Meadows', 'back', ['landmine'], 'horizontal-pull', ['lats', 'biceps']],
  ['Remada unilateral no landmine', 'back', ['landmine'], 'horizontal-pull', ['lats', 'biceps']],
  ['Remada serrote com halter', 'back', ['dumbbell', 'bench'], 'horizontal-pull', ['lats', 'biceps']],
  ['Remada apoiada com halteres', 'back', ['dumbbell', 'bench'], 'horizontal-pull', ['rear-delts', 'biceps']],
  ['Remada apoiada com barra', 'back', ['barbell', 'bench'], 'horizontal-pull', ['lats', 'biceps']],
  ['Remada articulada unilateral', 'back', ['machine'], 'horizontal-pull', ['lats', 'biceps']],
  ['Remada alta na máquina para costas', 'back', ['machine'], 'horizontal-pull', ['rear-delts', 'lats']],
  ['Remada invertida', 'back', ['bodyweight'], 'horizontal-pull', ['lats', 'biceps']],
  ['Remada invertida nas argolas', 'back', ['rings', 'bodyweight'], 'horizontal-pull', ['biceps', 'core']],
  ['Remada na fita de suspensão', 'back', ['suspension', 'bodyweight'], 'horizontal-pull', ['biceps', 'core']],
  ['Pulldown unilateral com braço estendido', 'lats', ['cable'], 'isolation', ['core']],
  ['Pulldown com corda', 'lats', ['cable'], 'isolation', ['back']],
  ['Pullover na polia', 'lats', ['cable'], 'isolation', ['chest']],
  ['Hiperextensão lombar no banco', 'lower-back', ['bench', 'bodyweight'], 'hinge', ['glutes', 'hamstrings']],
  ['Extensão lombar na máquina', 'lower-back', ['machine'], 'hinge', ['glutes']],
  ['Good morning com barra', 'lower-back', ['barbell'], 'hinge', ['hamstrings', 'glutes']],
  ['Good morning no Smith', 'lower-back', ['smith'], 'hinge', ['hamstrings', 'glutes']],

  // Ombros e trapézio
  ['Desenvolvimento militar com barra', 'front-delts', ['barbell'], 'vertical-push', ['side-delts', 'triceps']],
  ['Desenvolvimento militar no Smith', 'front-delts', ['smith', 'bench'], 'vertical-push', ['side-delts', 'triceps']],
  ['Desenvolvimento Arnold', 'front-delts', ['dumbbell', 'bench'], 'vertical-push', ['side-delts', 'triceps']],
  ['Desenvolvimento unilateral com halter', 'front-delts', ['dumbbell'], 'vertical-push', ['side-delts', 'triceps', 'core']],
  ['Desenvolvimento com kettlebell', 'front-delts', ['kettlebell'], 'vertical-push', ['triceps', 'core']],
  ['Desenvolvimento unilateral na polia', 'front-delts', ['cable'], 'vertical-push', ['triceps', 'core']],
  ['Desenvolvimento no landmine', 'front-delts', ['landmine'], 'vertical-push', ['chest', 'triceps']],
  ['Push press', 'front-delts', ['barbell'], 'vertical-push', ['triceps', 'quadriceps']],
  ['Elevação frontal com halteres', 'front-delts', ['dumbbell'], 'isolation'],
  ['Elevação frontal com barra', 'front-delts', ['barbell'], 'isolation'],
  ['Elevação frontal na polia', 'front-delts', ['cable'], 'isolation'],
  ['Elevação frontal com anilha', 'front-delts', ['plate'], 'isolation'],
  ['Elevação lateral unilateral com halter', 'side-delts', ['dumbbell'], 'isolation'],
  ['Elevação lateral na polia', 'side-delts', ['cable'], 'isolation'],
  ['Elevação lateral unilateral na polia', 'side-delts', ['cable'], 'isolation'],
  ['Elevação lateral na máquina', 'side-delts', ['machine'], 'isolation'],
  ['Elevação lateral inclinada com halter', 'side-delts', ['dumbbell', 'bench'], 'isolation'],
  ['Remada alta com barra', 'side-delts', ['barbell'], 'vertical-pull', ['traps', 'biceps']],
  ['Remada alta com halteres', 'side-delts', ['dumbbell'], 'vertical-pull', ['traps', 'biceps']],
  ['Remada alta na polia', 'side-delts', ['cable'], 'vertical-pull', ['traps', 'biceps']],
  ['Crucifixo inverso com halteres', 'rear-delts', ['dumbbell'], 'isolation', ['back']],
  ['Crucifixo inverso na polia', 'rear-delts', ['cable'], 'isolation', ['back']],
  ['Crucifixo inverso unilateral na polia', 'rear-delts', ['cable'], 'isolation', ['back']],
  ['Remada para deltoide posterior', 'rear-delts', ['dumbbell', 'bench'], 'horizontal-pull', ['back']],
  ['Face pull com elástico', 'rear-delts', ['band'], 'horizontal-pull', ['traps']],
  ['Encolhimento com barra', 'traps', ['barbell'], 'isolation'],
  ['Encolhimento no Smith', 'traps', ['smith'], 'isolation'],
  ['Encolhimento na máquina', 'traps', ['machine'], 'isolation'],
  ['Encolhimento na polia', 'traps', ['cable'], 'isolation'],
  ['Encolhimento com trap bar', 'traps', ['trap-bar'], 'isolation', ['forearms']],
  ['Elevação escapular na barra fixa', 'traps', ['bodyweight'], 'vertical-pull', ['lats']],

  // Bíceps, tríceps e antebraços
  ['Rosca direta com barra W', 'biceps', ['ez-bar'], 'isolation', ['forearms']],
  ['Rosca direta na polia', 'biceps', ['cable'], 'isolation', ['forearms']],
  ['Rosca direta na máquina', 'biceps', ['machine'], 'isolation', ['forearms']],
  ['Rosca simultânea com halteres', 'biceps', ['dumbbell'], 'isolation', ['forearms']],
  ['Rosca inclinada com halteres', 'biceps', ['dumbbell', 'bench'], 'isolation', ['forearms']],
  ['Rosca concentrada', 'biceps', ['dumbbell', 'bench'], 'isolation', ['forearms']],
  ['Rosca Scott com barra W', 'biceps', ['ez-bar', 'bench'], 'isolation', ['forearms']],
  ['Rosca Scott com halter', 'biceps', ['dumbbell', 'bench'], 'isolation', ['forearms']],
  ['Rosca Scott na máquina', 'biceps', ['machine'], 'isolation', ['forearms']],
  ['Rosca martelo alternada', 'biceps', ['dumbbell'], 'isolation', ['forearms']],
  ['Rosca martelo na polia com corda', 'biceps', ['cable'], 'isolation', ['forearms']],
  ['Rosca martelo cruzada', 'biceps', ['dumbbell'], 'isolation', ['forearms']],
  ['Rosca inversa com barra', 'forearms', ['barbell'], 'isolation', ['biceps']],
  ['Rosca inversa com barra W', 'forearms', ['ez-bar'], 'isolation', ['biceps']],
  ['Rosca inversa na polia', 'forearms', ['cable'], 'isolation', ['biceps']],
  ['Rosca Bayesian na polia', 'biceps', ['cable'], 'isolation', ['forearms']],
  ['Rosca spider com halteres', 'biceps', ['dumbbell', 'bench'], 'isolation', ['forearms']],
  ['Rosca spider com barra W', 'biceps', ['ez-bar', 'bench'], 'isolation', ['forearms']],
  ['Rosca 21 com barra', 'biceps', ['barbell'], 'isolation', ['forearms']],
  ['Rosca Zottman', 'biceps', ['dumbbell'], 'isolation', ['forearms']],
  ['Tríceps corda unilateral', 'triceps', ['cable'], 'isolation'],
  ['Tríceps barra reta na polia', 'triceps', ['cable'], 'isolation'],
  ['Tríceps barra V na polia', 'triceps', ['cable'], 'isolation'],
  ['Tríceps unilateral na polia pegada neutra', 'triceps', ['cable'], 'isolation'],
  ['Tríceps unilateral na polia pegada supinada', 'triceps', ['cable'], 'isolation'],
  ['Tríceps francês com dois halteres', 'triceps', ['dumbbell'], 'isolation'],
  ['Tríceps francês unilateral com halter', 'triceps', ['dumbbell'], 'isolation'],
  ['Tríceps francês na polia', 'triceps', ['cable'], 'isolation'],
  ['Tríceps testa com barra W', 'triceps', ['ez-bar', 'bench'], 'isolation'],
  ['Tríceps testa com halteres', 'triceps', ['dumbbell', 'bench'], 'isolation'],
  ['Tríceps testa na polia', 'triceps', ['cable', 'bench'], 'isolation'],
  ['Tríceps coice com halter', 'triceps', ['dumbbell'], 'isolation'],
  ['Tríceps coice na polia', 'triceps', ['cable'], 'isolation'],
  ['Tríceps na máquina', 'triceps', ['machine'], 'isolation'],
  ['Mergulho entre bancos', 'triceps', ['bodyweight', 'bench'], 'vertical-push', ['chest']],
  ['Mergulho assistido na máquina', 'triceps', ['machine'], 'vertical-push', ['chest', 'front-delts']],
  ['Mergulho nas paralelas para tríceps', 'triceps', ['bodyweight'], 'vertical-push', ['chest']],
  ['Extensão de punho com halter', 'forearms', ['dumbbell'], 'isolation'],
  ['Flexão de punho com barra', 'forearms', ['barbell'], 'isolation'],
  ['Extensão de punho com barra', 'forearms', ['barbell'], 'isolation'],
  ['Flexão de punho na polia', 'forearms', ['cable'], 'isolation'],
  ['Desvio radial com halter', 'forearms', ['dumbbell'], 'isolation'],
  ['Pronação e supinação com halter', 'forearms', ['dumbbell'], 'isolation'],
  ['Rosca de punho atrás do corpo', 'forearms', ['barbell'], 'isolation'],
  ['Farmer hold com halteres', 'forearms', ['dumbbell'], 'carry', ['traps', 'core']],

  // Quadríceps, posteriores e glúteos
  ['Agachamento frontal com barra', 'quadriceps', ['barbell'], 'squat', ['glutes', 'core']],
  ['Agachamento frontal no Smith', 'quadriceps', ['smith'], 'squat', ['glutes']],
  ['Agachamento sumô com barra', 'glutes', ['barbell'], 'squat', ['adductors', 'quadriceps']],
  ['Agachamento sumô com halter', 'glutes', ['dumbbell'], 'squat', ['adductors', 'quadriceps']],
  ['Agachamento sumô no Smith', 'glutes', ['smith'], 'squat', ['adductors', 'quadriceps']],
  ['Agachamento hack', 'quadriceps', ['machine'], 'squat', ['glutes']],
  ['Agachamento pendular', 'quadriceps', ['machine'], 'squat', ['glutes']],
  ['Agachamento no belt squat', 'quadriceps', ['machine'], 'squat', ['glutes']],
  ['Agachamento sissy', 'quadriceps', ['bodyweight'], 'squat'],
  ['Agachamento sissy na máquina', 'quadriceps', ['machine'], 'squat'],
  ['Agachamento pistol', 'quadriceps', ['bodyweight'], 'squat', ['glutes', 'core']],
  ['Agachamento com kettlebell duplo', 'quadriceps', ['kettlebell'], 'squat', ['glutes', 'core']],
  ['Agachamento búlgaro com halteres', 'quadriceps', ['dumbbell', 'bench'], 'squat', ['glutes', 'hamstrings']],
  ['Agachamento búlgaro com barra', 'quadriceps', ['barbell', 'bench'], 'squat', ['glutes', 'hamstrings']],
  ['Agachamento búlgaro no Smith', 'quadriceps', ['smith', 'bench'], 'squat', ['glutes', 'hamstrings']],
  ['Agachamento búlgaro com peso corporal', 'quadriceps', ['bodyweight', 'bench'], 'squat', ['glutes']],
  ['Afundo com barra', 'quadriceps', ['barbell'], 'squat', ['glutes', 'hamstrings']],
  ['Afundo no Smith', 'quadriceps', ['smith'], 'squat', ['glutes']],
  ['Afundo reverso com halteres', 'quadriceps', ['dumbbell'], 'squat', ['glutes']],
  ['Afundo reverso na polia', 'quadriceps', ['cable'], 'squat', ['glutes']],
  ['Afundo lateral com halter', 'adductors', ['dumbbell'], 'squat', ['glutes', 'quadriceps']],
  ['Passada com barra', 'quadriceps', ['barbell'], 'squat', ['glutes', 'hamstrings']],
  ['Passada no Smith', 'quadriceps', ['smith'], 'squat', ['glutes']],
  ['Passada caminhando com halteres', 'quadriceps', ['dumbbell'], 'squat', ['glutes', 'hamstrings']],
  ['Step-up com halteres', 'quadriceps', ['dumbbell', 'step'], 'squat', ['glutes']],
  ['Step-up com barra', 'quadriceps', ['barbell', 'step'], 'squat', ['glutes']],
  ['Step-down unilateral', 'quadriceps', ['bodyweight', 'step'], 'squat', ['glutes']],
  ['Leg press horizontal', 'quadriceps', ['leg-press'], 'squat', ['glutes']],
  ['Leg press vertical', 'quadriceps', ['leg-press'], 'squat', ['glutes', 'hamstrings']],
  ['Leg press unilateral', 'quadriceps', ['leg-press'], 'squat', ['glutes']],
  ['Cadeira extensora unilateral', 'quadriceps', ['machine'], 'knee-extension'],
  ['Extensão de joelhos na polia', 'quadriceps', ['cable'], 'knee-extension'],
  ['Spanish squat com elástico', 'quadriceps', ['band'], 'squat'],
  ['Stiff com halteres', 'hamstrings', ['dumbbell'], 'hinge', ['glutes']],
  ['Stiff no Smith', 'hamstrings', ['smith'], 'hinge', ['glutes']],
  ['Stiff unilateral com halter', 'hamstrings', ['dumbbell'], 'hinge', ['glutes', 'core']],
  ['Levantamento terra romeno com barra', 'hamstrings', ['barbell'], 'hinge', ['glutes', 'lower-back']],
  ['Levantamento terra romeno no Smith', 'hamstrings', ['smith'], 'hinge', ['glutes']],
  ['Levantamento terra romeno unilateral', 'hamstrings', ['dumbbell'], 'hinge', ['glutes', 'core']],
  ['Levantamento terra sumô', 'glutes', ['barbell'], 'hinge', ['adductors', 'hamstrings']],
  ['Levantamento terra com trap bar', 'glutes', ['trap-bar'], 'hinge', ['quadriceps', 'hamstrings', 'back']],
  ['Levantamento terra em déficit', 'glutes', ['barbell', 'step'], 'hinge', ['hamstrings', 'back']],
  ['Rack pull', 'back', ['barbell'], 'hinge', ['glutes', 'lower-back']],
  ['Cadeira flexora unilateral', 'hamstrings', ['machine'], 'knee-flexion'],
  ['Mesa flexora unilateral', 'hamstrings', ['machine'], 'knee-flexion'],
  ['Flexora em pé unilateral', 'hamstrings', ['machine'], 'knee-flexion'],
  ['Flexão de joelhos na polia', 'hamstrings', ['cable'], 'knee-flexion'],
  ['Flexão nórdica', 'hamstrings', ['bodyweight'], 'knee-flexion', ['glutes']],
  ['Flexão de joelhos na bola suíça', 'hamstrings', ['stability-ball', 'bodyweight'], 'knee-flexion', ['glutes', 'core']],
  ['Glute ham raise', 'hamstrings', ['machine'], 'knee-flexion', ['glutes', 'lower-back']],
  ['Hip thrust com halter', 'glutes', ['dumbbell', 'bench'], 'hinge', ['hamstrings']],
  ['Hip thrust no Smith', 'glutes', ['smith', 'bench'], 'hinge', ['hamstrings']],
  ['Hip thrust na máquina', 'glutes', ['machine'], 'hinge', ['hamstrings']],
  ['Hip thrust unilateral', 'glutes', ['bodyweight', 'bench'], 'hinge', ['hamstrings']],
  ['Ponte de glúteos com barra', 'glutes', ['barbell'], 'hinge', ['hamstrings']],
  ['Ponte de glúteos com halter', 'glutes', ['dumbbell'], 'hinge', ['hamstrings']],
  ['Ponte de glúteos unilateral', 'glutes', ['bodyweight'], 'hinge', ['hamstrings', 'core']],
  ['Coice de glúteo na polia', 'glutes', ['cable'], 'isolation', ['hamstrings']],
  ['Coice de glúteo na máquina', 'glutes', ['machine'], 'isolation', ['hamstrings']],
  ['Coice de glúteo com elástico', 'glutes', ['band'], 'isolation', ['hamstrings']],
  ['Abdução de quadril na polia', 'glutes', ['cable'], 'isolation'],
  ['Abdução de quadril com elástico', 'glutes', ['band'], 'isolation'],
  ['Abdução lateral deitada', 'glutes', ['bodyweight'], 'isolation'],
  ['Caminhada lateral com elástico', 'glutes', ['band'], 'locomotion'],
  ['Frog pump', 'glutes', ['bodyweight'], 'hinge'],
  ['Extensão de quadril no banco romano', 'glutes', ['bench', 'bodyweight'], 'hinge', ['hamstrings', 'lower-back']],
  ['Pull-through na polia', 'glutes', ['cable'], 'hinge', ['hamstrings']],
  ['Adução de quadril na polia', 'adductors', ['cable'], 'isolation'],
  ['Adução de quadril com elástico', 'adductors', ['band'], 'isolation'],
  ['Prancha Copenhagen', 'adductors', ['bodyweight', 'bench'], 'core', ['core']],
  ['Elevação de joelhos na máquina', 'hip-flexors', ['machine'], 'core', ['core']],
  ['Marcha com elástico para flexores do quadril', 'hip-flexors', ['band'], 'isolation', ['core']],

  // Panturrilhas e tibial anterior
  ['Panturrilha em pé com halteres', 'calves', ['dumbbell'], 'calf'],
  ['Panturrilha em pé com barra', 'calves', ['barbell'], 'calf'],
  ['Panturrilha em pé no Smith', 'calves', ['smith'], 'calf'],
  ['Panturrilha em pé na máquina', 'calves', ['machine'], 'calf'],
  ['Panturrilha sentado com halter', 'calves', ['dumbbell', 'bench'], 'calf'],
  ['Panturrilha sentado no Smith', 'calves', ['smith', 'bench'], 'calf'],
  ['Panturrilha no leg press', 'calves', ['leg-press'], 'calf'],
  ['Panturrilha no hack', 'calves', ['machine'], 'calf'],
  ['Panturrilha donkey', 'calves', ['machine'], 'calf'],
  ['Panturrilha unilateral com halter', 'calves', ['dumbbell'], 'calf'],
  ['Panturrilha no step com peso corporal', 'calves', ['bodyweight', 'step'], 'calf'],
  ['Elevação do tibial anterior na parede', 'tibialis', ['bodyweight'], 'isolation'],
  ['Elevação do tibial anterior na máquina', 'tibialis', ['machine'], 'isolation'],
  ['Dorsiflexão com elástico', 'tibialis', ['band'], 'isolation'],

  // Core
  ['Prancha lateral', 'core', ['bodyweight'], 'core'],
  ['Prancha com apoio nos braços estendidos', 'core', ['bodyweight'], 'core'],
  ['Prancha com toque nos ombros', 'core', ['bodyweight'], 'core'],
  ['Prancha com carga', 'core', ['plate', 'bodyweight'], 'core'],
  ['Prancha na bola suíça', 'core', ['stability-ball', 'bodyweight'], 'core'],
  ['Body saw na fita de suspensão', 'core', ['suspension', 'bodyweight'], 'core'],
  ['Abdominal infra', 'core', ['bodyweight'], 'core', ['hip-flexors']],
  ['Abdominal bicicleta', 'core', ['bodyweight'], 'rotation', ['hip-flexors']],
  ['Abdominal remador', 'core', ['bodyweight'], 'core', ['hip-flexors']],
  ['Abdominal canivete', 'core', ['bodyweight'], 'core', ['hip-flexors']],
  ['Abdominal na máquina', 'core', ['machine'], 'core'],
  ['Abdominal declinado', 'core', ['bench', 'bodyweight'], 'core'],
  ['Abdominal na bola suíça', 'core', ['stability-ball', 'bodyweight'], 'core'],
  ['Elevação de joelhos na barra', 'core', ['bodyweight'], 'core', ['hip-flexors']],
  ['Elevação de pernas na barra', 'core', ['bodyweight'], 'core', ['hip-flexors']],
  ['Elevação de joelhos nas paralelas', 'core', ['bodyweight'], 'core', ['hip-flexors']],
  ['Elevação de pernas no banco', 'core', ['bench', 'bodyweight'], 'core', ['hip-flexors']],
  ['Roda abdominal ajoelhado', 'core', ['ab-wheel'], 'core'],
  ['Roda abdominal em pé', 'core', ['ab-wheel'], 'core'],
  ['Pallof press', 'core', ['cable'], 'rotation'],
  ['Pallof press com elástico', 'core', ['band'], 'rotation'],
  ['Wood chop na polia alta', 'core', ['cable'], 'rotation'],
  ['Wood chop na polia baixa', 'core', ['cable'], 'rotation'],
  ['Rotação de tronco na máquina', 'core', ['machine'], 'rotation'],
  ['Russian twist com medicine ball', 'core', ['medicine-ball'], 'rotation'],
  ['Dead bug', 'core', ['bodyweight'], 'core'],
  ['Bird dog', 'core', ['bodyweight'], 'core', ['lower-back', 'glutes']],
  ['Hollow body hold', 'core', ['bodyweight'], 'core'],
  ['Superman', 'lower-back', ['bodyweight'], 'hinge', ['glutes']],

  // Corpo inteiro, potência, carregadas e condicionamento
  ['Farmer walk com halteres', 'full-body', ['dumbbell'], 'carry', ['forearms', 'traps', 'core']],
  ['Farmer walk com trap bar', 'full-body', ['trap-bar'], 'carry', ['forearms', 'traps', 'core']],
  ['Suitcase carry com halter', 'core', ['dumbbell'], 'carry', ['forearms', 'traps']],
  ['Overhead carry com kettlebell', 'core', ['kettlebell'], 'carry', ['front-delts', 'traps']],
  ['Kettlebell swing', 'full-body', ['kettlebell'], 'hinge', ['glutes', 'hamstrings', 'core']],
  ['Kettlebell clean', 'full-body', ['kettlebell'], 'olympic', ['glutes', 'front-delts']],
  ['Kettlebell snatch', 'full-body', ['kettlebell'], 'olympic', ['glutes', 'front-delts']],
  ['Levantamento olímpico clean', 'full-body', ['barbell'], 'olympic', ['quadriceps', 'glutes', 'traps']],
  ['Power clean', 'full-body', ['barbell'], 'olympic', ['quadriceps', 'glutes', 'traps']],
  ['Snatch com barra', 'full-body', ['barbell'], 'olympic', ['quadriceps', 'glutes', 'traps']],
  ['Thruster com barra', 'full-body', ['barbell'], 'vertical-push', ['quadriceps', 'glutes', 'front-delts']],
  ['Thruster com halteres', 'full-body', ['dumbbell'], 'vertical-push', ['quadriceps', 'glutes', 'front-delts']],
  ['Burpee', 'full-body', ['bodyweight'], 'locomotion', ['chest', 'quadriceps', 'core']],
  ['Mountain climber', 'full-body', ['bodyweight'], 'locomotion', ['core', 'hip-flexors']],
  ['Box jump', 'quadriceps', ['step'], 'plyometric', ['glutes', 'calves']],
  ['Salto agachado', 'quadriceps', ['bodyweight'], 'plyometric', ['glutes', 'calves']],
  ['Salto lateral', 'full-body', ['bodyweight'], 'plyometric', ['glutes', 'calves']],
  ['Empurrar trenó', 'full-body', ['sled'], 'locomotion', ['quadriceps', 'glutes', 'calves']],
  ['Puxar trenó', 'full-body', ['sled'], 'locomotion', ['back', 'quadriceps', 'glutes']],
  ['Corda naval ondas alternadas', 'full-body', ['battle-rope'], 'locomotion', ['front-delts', 'core']],
  ['Medicine ball slam', 'full-body', ['medicine-ball'], 'plyometric', ['lats', 'core']],
  ['Arremesso de medicine ball na parede', 'full-body', ['medicine-ball'], 'plyometric', ['chest', 'core']],

  // Pescoço
  ['Flexão cervical deitado', 'neck', ['bodyweight'], 'isolation'],
  ['Extensão cervical deitado', 'neck', ['bodyweight'], 'isolation'],
  ['Flexão lateral cervical', 'neck', ['bodyweight'], 'isolation'],
  ['Flexão cervical com elástico', 'neck', ['band'], 'isolation'],
  ['Extensão cervical com elástico', 'neck', ['band'], 'isolation'],

  // Aquecimento e saúde dos ombros (adicionado ao final para preservar IDs existentes)
  ['Aquecimento de manguito rotador na polia', 'rotator-cuff', ['cable'], 'isolation', ['rear-delts']],
  ['Tríceps testa na máquina', 'triceps', ['machine'], 'isolation'],
] as const;
