import { useCallback, useEffect, useMemo, useState } from 'react';
import { RoutineService, type RoutineSnapshot } from '../../application/routine/routine-service';
import { averageSleepMinutes, formatDuration, type RoutineDay, type RoutineProfile } from '../../domain/routine/routine';
import { DAY_LABELS, TRAINING_DAYS, type TrainingDay } from '../../domain/training/training';
import { repositories } from '../../infrastructure/repositories';
import { Button } from '../../shared/components/Button';
import './routine-workspace.css';

const service = new RoutineService(repositories.routine, repositories.workoutPlans, repositories.workoutSessions);
const LONG_DAY: Record<TrainingDay, string> = { monday: 'Segunda', tuesday: 'Terça', wednesday: 'Quarta', thursday: 'Quinta', friday: 'Sexta', saturday: 'Sábado', sunday: 'Domingo' };

export function RoutineWorkspace({ profileId, revision, onChanged, onNotice }: { profileId: string; revision: number; onChanged: () => void; onNotice: (message: string) => void }) {
  const [data, setData] = useState<RoutineSnapshot>();
  const [editing, setEditing] = useState<RoutineDay>();
  const [sleepOpen, setSleepOpen] = useState(false);
  const [settingsOpen, setSettingsOpen] = useState(false);
  const [error, setError] = useState('');
  const load = useCallback(() => service.load(profileId).then(setData).catch((caught: unknown) => setError(caught instanceof Error ? caught.message : 'Não foi possível abrir a rotina.')), [profileId]);
  useEffect(() => { void load(); }, [load, revision]);
  if (error) return <div className="page-state error-state" role="alert"><strong>Não foi possível abrir a rotina.</strong><p>{error}</p></div>;
  if (!data) return <div className="routine-loading" aria-label="Carregando rotina" />;
  const todayTemplate = data.templates.find((item) => item.id === data.today.workoutTemplateId);
  const todayEvents = ([
    data.today.wakeTime ? { time: data.today.wakeTime, label: 'Acordar' } : undefined,
    data.today.workoutTime ? { time: data.today.workoutTime, label: todayTemplate?.name ?? 'Treino' } : undefined,
    data.today.sleepTime ? { time: data.today.sleepTime, label: 'Horário habitual de sono' } : undefined,
  ].filter((event): event is { time: string; label: string } => Boolean(event))).sort((a, b) => a.time.localeCompare(b.time));

  return <div className="routine-page">
    <header className="routine-header"><div><span className="page-eyebrow">Seu ritmo, sem julgamentos</span><h1>Rotina</h1><p>Organize horários habituais, sono, treino e lembretes locais. Campos vazios continuam sem registro.</p></div><Button variant="secondary" compact onClick={() => setSettingsOpen(true)}>Lembretes</Button></header>

    <section className="routine-today">
      <div><span className="page-eyebrow">Hoje · {LONG_DAY[data.today.dayOfWeek]}</span><h2>{todayEvents.length ? 'Linha do tempo' : 'Dia sem horários definidos'}</h2><p>{data.sleep ? `Sono registrado: ${formatDuration(data.sleep.durationMinutes)}.` : 'Sono: sem registro hoje.'}</p></div>
      <div className="routine-timeline">{todayEvents.length ? todayEvents.map((event) => <article key={`${event.time}-${event.label}`}><time>{event.time}</time><i aria-hidden="true"/><strong>{event.label}</strong></article>) : <p>Você pode adicionar apenas os horários que fizerem sentido.</p>}</div>
      <Button onClick={() => setSleepOpen(true)}>{data.sleep ? 'Editar sono' : 'Registrar sono'}</Button>
    </section>

    <section className="routine-week"><header><div><span className="page-eyebrow">Semana</span><h2>Planejamento habitual</h2></div><small>O treino acompanha o nome da ficha ativa.</small></header><div className="routine-day-list">{data.days.map((day) => { const template = data.templates.find((item) => item.id === day.workoutTemplateId); return <button key={day.dayOfWeek} type="button" className={day.dayOfWeek === data.today.dayOfWeek ? 'today' : ''} onClick={() => setEditing(day)}><span><b>{DAY_LABELS[day.dayOfWeek]}</b><small>{day.dayOfWeek === data.today.dayOfWeek ? 'Hoje' : LONG_DAY[day.dayOfWeek]}</small></span><strong>{day.isRestDay ? 'Descanso' : template?.name ?? 'Sem treino definido'}</strong><em>{[day.wakeTime && `Acordar ${day.wakeTime}`, day.workoutTime && `Treino ${day.workoutTime}`, day.sleepTime && `Sono ${day.sleepTime}`].filter(Boolean).join(' · ') || 'Sem horários definidos'}</em><i aria-hidden="true">→</i></button>; })}</div></section>

    <section className="sleep-history"><header><div><span className="page-eyebrow">Sono real</span><h2>Registros recentes</h2></div><strong>Média: {formatDuration(averageSleepMinutes(data.recentSleep))}</strong></header>{data.recentSleep.length ? <ul>{data.recentSleep.slice(0, 7).map((record) => <li key={record.id}><time>{new Intl.DateTimeFormat('pt-BR').format(new Date(`${record.localDate}T12:00:00`))}</time><strong>{formatDuration(record.durationMinutes)}</strong><span>{record.note || 'Sem nota'}</span><button onClick={async () => { await service.removeSleep(profileId, record.id); await load(); onChanged(); }}>Excluir</button></li>)}</ul> : <p className="routine-empty">Sem registros. Médias só aparecem depois do primeiro registro real.</p>}</section>

    {editing && <DayEditor day={editing} templates={data.templates} onClose={() => setEditing(undefined)} onSave={async (day, copyTo) => { await service.saveDay(day); if (copyTo.length) await service.copyDay(day, copyTo); setEditing(undefined); await load(); onChanged(); onNotice('Rotina do dia salva neste dispositivo.'); }} />}
    {sleepOpen && <SleepEditor existing={data.sleep} onClose={() => setSleepOpen(false)} onSave={async (start, wake, note) => { await service.recordSleep(profileId, start, wake, note); setSleepOpen(false); await load(); onChanged(); onNotice('Sono registrado. A data usada é a do despertar.'); }} />}
    {settingsOpen && <ReminderSettings profile={data.profile} onClose={() => setSettingsOpen(false)} onSave={async (profile) => { await service.savePreferences(profile); setSettingsOpen(false); await load(); onChanged(); onNotice('Preferências de lembretes salvas.'); }} onSnooze={async (until) => { await Promise.all((['water','workout','check-in','sleep'] as const).map((kind) => service.snooze(profileId, kind, until))); onNotice(`Lembretes silenciados até ${new Intl.DateTimeFormat('pt-BR',{day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit'}).format(until)}.`); }} onPermission={async () => { const permission = await service.requestNotificationPermission(); const profile = { ...data.profile, notificationPermission: permission }; await service.savePreferences(profile); await load(); onNotice(permission === 'granted' ? 'Notificações locais autorizadas.' : permission === 'denied' ? 'Notificações bloqueadas pelo navegador.' : 'Notificações não estão disponíveis neste navegador.'); }} />}
  </div>;
}

function Sheet({ title, eyebrow, onClose, children }: { title: string; eyebrow: string; onClose: () => void; children: React.ReactNode }) { return <div className="routine-sheet-backdrop" onMouseDown={(event) => { if (event.target === event.currentTarget) onClose(); }}><section className="routine-sheet" role="dialog" aria-modal="true" aria-label={title} data-pwa-update-blocking="true"><header><div><span className="page-eyebrow">{eyebrow}</span><h2>{title}</h2></div><button type="button" onClick={onClose} aria-label="Fechar">×</button></header>{children}</section></div>; }

function DayEditor({ day, templates, onClose, onSave }: { day: RoutineDay; templates: RoutineSnapshot['templates']; onClose: () => void; onSave: (day: RoutineDay, copyTo: TrainingDay[]) => Promise<void> }) {
  const [draft, setDraft] = useState(day); const [copyTo, setCopyTo] = useState<TrainingDay[]>([]); const [busy, setBusy] = useState(false);
  return <Sheet eyebrow="Editar dia" title={LONG_DAY[day.dayOfWeek]} onClose={onClose}><form className="routine-form" onSubmit={async (event) => { event.preventDefault(); setBusy(true); try { await onSave(draft, copyTo); } finally { setBusy(false); } }}>
    <div className="routine-time-grid"><label>Acordar <input type="time" value={draft.wakeTime ?? ''} onChange={(event) => setDraft({ ...draft, wakeTime: event.target.value || undefined })}/></label><label>Dormir <input type="time" value={draft.sleepTime ?? ''} onChange={(event) => setDraft({ ...draft, sleepTime: event.target.value || undefined })}/></label><label>Treino aproximado <input type="time" value={draft.workoutTime ?? ''} onChange={(event) => setDraft({ ...draft, workoutTime: event.target.value || undefined })}/></label></div>
    <label>Treino da ficha <select value={draft.workoutTemplateId ?? ''} onChange={(event) => setDraft({ ...draft, workoutTemplateId: event.target.value || undefined, isRestDay: false })}><option value="">Sem treino definido</option>{templates.map((template) => <option key={template.id} value={template.id}>{template.name}</option>)}</select></label>
    <label className="routine-check"><input type="checkbox" checked={draft.isRestDay} onChange={(event) => setDraft({ ...draft, isRestDay: event.target.checked, workoutTemplateId: event.target.checked ? undefined : draft.workoutTemplateId })}/><span>Marcar como dia de descanso</span></label>
    <fieldset><legend>Copiar esta configuração para</legend><div className="copy-days">{TRAINING_DAYS.filter((value) => value !== day.dayOfWeek).map((value) => <label key={value}><input type="checkbox" checked={copyTo.includes(value)} onChange={(event) => setCopyTo(event.target.checked ? [...copyTo, value] : copyTo.filter((item) => item !== value))}/><span>{DAY_LABELS[value]}</span></label>)}</div></fieldset>
    <p className="routine-disclosure">Horário ausente permanece indefinido; o DEFYN nunca o transforma em 00:00.</p><div className="routine-form-actions"><Button variant="secondary" type="button" onClick={onClose}>Cancelar</Button><Button loading={busy} type="submit">Salvar dia</Button></div>
  </form></Sheet>;
}

function localInput(date: Date) { const offset = date.getTimezoneOffset() * 60_000; return new Date(date.getTime() - offset).toISOString().slice(0, 16); }
function SleepEditor({ existing, onClose, onSave }: { existing?: RoutineSnapshot['sleep']; onClose: () => void; onSave: (start: string, wake: string, note: string) => Promise<void> }) {
  const defaults = useMemo(() => { const wake = existing ? new Date(existing.wokeAt) : new Date(); const start = existing ? new Date(existing.sleepStartedAt) : new Date(wake.getTime() - 8 * 3_600_000); return { start: localInput(start), wake: localInput(wake) }; }, [existing]);
  const [start, setStart] = useState(defaults.start); const [wake, setWake] = useState(defaults.wake); const [note, setNote] = useState(existing?.note ?? ''); const [busy, setBusy] = useState(false); const [error, setError] = useState('');
  return <Sheet eyebrow="Registro factual" title="Sono" onClose={onClose}><form className="routine-form" onSubmit={async (event) => { event.preventDefault(); setBusy(true); setError(''); try { await onSave(start, wake, note); } catch (caught) { setError(caught instanceof Error ? caught.message : 'Confira os horários.'); } finally { setBusy(false); } }}><div className="routine-time-grid"><label>Início do sono <input required type="datetime-local" value={start} onChange={(event) => setStart(event.target.value)}/></label><label>Despertar <input required type="datetime-local" value={wake} onChange={(event) => setWake(event.target.value)}/></label></div><label>Nota opcional <textarea value={note} onChange={(event) => setNote(event.target.value)} placeholder="Contexto que você queira lembrar."/></label><p className="routine-disclosure">O registro pertence à data do despertar. Viradas de meia-noite são calculadas pelos horários completos.</p>{error && <p className="routine-error" role="alert">{error}</p>}<div className="routine-form-actions"><Button variant="secondary" type="button" onClick={onClose}>Cancelar</Button><Button loading={busy}>Salvar sono</Button></div></form></Sheet>;
}

function ReminderSettings({ profile, onClose, onSave, onPermission, onSnooze }: { profile: RoutineProfile; onClose: () => void; onSave: (profile: RoutineProfile) => Promise<void>; onPermission: () => Promise<void>; onSnooze: (until: Date) => Promise<void> }) {
  const [draft, setDraft] = useState(profile); const [busy, setBusy] = useState(false); const permissionLabel = { default: 'Ainda não solicitado', granted: 'Permitido', denied: 'Bloqueado', unsupported: 'Não suportado' }[profile.notificationPermission];
  return <Sheet eyebrow="Opt-in local" title="Lembretes" onClose={onClose}><div className="routine-form"><aside className="notification-state"><span>Permissão do navegador</span><strong>{permissionLabel}</strong>{profile.notificationPermission === 'default' && <Button compact type="button" onClick={() => void onPermission()}>Autorizar notificações</Button>}</aside><p className="routine-disclosure">Os lembretes dependem do navegador e do sistema. Não há push remoto nem garantia de execução com o app fechado.</p>{(['water','workout','checkIn','sleep'] as const).map((key) => <label key={key} className="reminder-toggle"><span><strong>{{water:'Água',workout:'Treino',checkIn:'Check-in semanal',sleep:'Sono'}[key]}</strong><small>{{water:'Respeita meta, registro recente e pausa.',workout:'Não aparece se o treino terminou ou está ativo.',checkIn:'Um lembrete no dia escolhido.',sleep:'Antes do horário habitual.'}[key]}</small></span><input type="checkbox" checked={draft.reminders[key]} onChange={(event) => setDraft({ ...draft, reminders: { ...draft.reminders, [key]: event.target.checked } })}/></label>)}<div className="routine-time-grid"><label>Silêncio a partir de <input type="time" value={draft.reminders.quietHoursStart ?? ''} onChange={(event) => setDraft({ ...draft, reminders: { ...draft.reminders, quietHoursStart: event.target.value || undefined } })}/></label><label>Silêncio até <input type="time" value={draft.reminders.quietHoursEnd ?? ''} onChange={(event) => setDraft({ ...draft, reminders: { ...draft.reminders, quietHoursEnd: event.target.value || undefined } })}/></label></div><fieldset><legend>Silenciar todos agora</legend><div className="reminder-snooze"><button type="button" onClick={() => void onSnooze(new Date(Date.now()+3_600_000))}>Por 1 hora</button><button type="button" onClick={() => { const end=new Date(); end.setHours(23,59,59,999); void onSnooze(end); }}>Hoje</button><button type="button" onClick={() => void onSnooze(new Date(Date.now()+24*3_600_000))}>Até amanhã</button></div></fieldset><div className="routine-form-actions"><Button variant="secondary" onClick={onClose}>Cancelar</Button><Button loading={busy} onClick={async () => { setBusy(true); try { await onSave(draft); } finally { setBusy(false); } }}>Salvar lembretes</Button></div></div></Sheet>;
}
