import { useCallback, useEffect, useMemo, useRef, useState, type ChangeEvent, type FormEvent } from 'react';
import type { AppView } from '../../app/navigation';
import { FoodService } from '../../application/food/food-service';
import { DiaryService } from '../../application/diary/diary-service';
import { optimizeImage, type ImageProcessingTimings } from '../../application/media/image-processing';
import { cancelNutritionLabelRecognition, describeOcrProgress, recognizeNutritionLabel, type OcrTimings } from '../../application/ocr/local-ocr';
import type { DiaryEntry, FavoriteMeal, MealCategory } from '../../domain/diary/diary';
import { totalDiaryNutrients } from '../../domain/diary/diary';
import { normalizeFoodSearch, scaleNutrients, type Food, type NutrientValues, type PortionUnit } from '../../domain/food/food';
import { parseBrazilianNutritionLabel } from '../../domain/food/nutrition-label-parser';
import { calculateRecipeNutrition, type Recipe } from '../../domain/recipe/recipe';
import { planDailyMeals } from '../../domain/planner/meal-planner';
import type { UserProfile } from '../../domain/profile/profile';
import { toLocalDateKey } from '../../domain/shared/local-date';
import { repositories } from '../../infrastructure/repositories';
import { DefynSelect } from '../../shared/components/DefynSelect';
import { MacroLegend } from '../../shared/components/MacroLegend';
import { browserCapabilities } from '../../platform/device-capabilities';
import './nutrition-workspace.css';

const foodService = new FoodService(repositories.foods);
const diaryService = new DiaryService(repositories.diary);
const number = (value: string) => value.trim() === '' ? undefined : Number(value.replace(',', '.'));
const show = (value: number | undefined, suffix = '') => value === undefined ? '—' : `${Math.round(value * 10) / 10}${suffix}`;

export function NutritionWorkspace({ view, profile, revision, onChanged, onNotice }: { view: Extract<AppView, 'foods' | 'diary' | 'recipes' | 'planner'>; profile: UserProfile; revision: number; onChanged: () => void; onNotice: (message: string) => void }) {
  if (view === 'foods') return <FoodsPage profile={profile} revision={revision} onChanged={onChanged} onNotice={onNotice} />;
  if (view === 'diary') return <DiaryPage profile={profile} revision={revision} onChanged={onChanged} onNotice={onNotice} />;
  if (view === 'recipes') return <RecipesPage profile={profile} revision={revision} onChanged={onChanged} onNotice={onNotice} />;
  return <PlannerPage profile={profile} revision={revision} />;
}

type FoodDraft = { name: string; brand: string; category: string; barcode: string; quantity: string; unit: PortionUnit; calories: string; protein: string; carbs: string; fat: string; fiber: string; sodium: string; saturatedFat: string; sugars: string; addedSugars: string; };
type OcrAttemptTimings = OcrTimings & { image?: ImageProcessingTimings; parserMs: number; totalAttemptMs: number };
const emptyFood: FoodDraft = { name: '', brand: '', category: '', barcode: '', quantity: '100', unit: 'g', calories: '', protein: '', carbs: '', fat: '', fiber: '', sodium: '', saturatedFat: '', sugars: '', addedSugars: '' };

function FoodsPage({ profile, revision, onChanged, onNotice }: { profile: UserProfile; revision: number; onChanged: () => void; onNotice: (message: string) => void }) {
  const capabilities = useMemo(() => browserCapabilities(), []); const cameraInput = useRef<HTMLInputElement>(null); const galleryInput = useRef<HTMLInputElement>(null);
  const [foods, setFoods] = useState<Food[]>([]); const [query, setQuery] = useState(''); const [editor, setEditor] = useState<'manual' | 'ocr'>(); const [ocrManualMode, setOcrManualMode] = useState(false);
  const [draft, setDraft] = useState<FoodDraft>(emptyFood); const [advanced, setAdvanced] = useState(false); const [busy, setBusy] = useState(''); const [error, setError] = useState('');
  const [labelMedia, setLabelMedia] = useState<Awaited<ReturnType<typeof optimizeImage>>>(); const [ocrText, setOcrText] = useState(''); const [favorites, setFavorites] = useState<Set<string>>(new Set());
  const [labelFile, setLabelFile] = useState<File>(); const [rotation, setRotation] = useState<0|1|2|3>(0); const [cropInset, setCropInset] = useState(0); const [enhanceOcr, setEnhanceOcr] = useState(true);
  const [ocrTimings, setOcrTimings] = useState<OcrAttemptTimings>(); const [ocrColumns, setOcrColumns] = useState<{ portion?: NutrientValues; per100?: NutrientValues }>(); const [ocrPortion, setOcrPortion] = useState<{ quantity: number; unit: PortionUnit }>(); const [ocrBasis, setOcrBasis] = useState<'portion'|'per100'>('portion'); const [previewZoom, setPreviewZoom] = useState(false);
  const [duplicates, setDuplicates] = useState<Food[]>([]); const [portionLabel, setPortionLabel] = useState(''); const [portionEquivalent, setPortionEquivalent] = useState('');
  const [ocrWarnings, setOcrWarnings] = useState<string[]>([]); const [keepLabelPhoto, setKeepLabelPhoto] = useState(false); const labelPreview = useMemo(() => labelMedia ? URL.createObjectURL(labelMedia.blob) : '', [labelMedia]); const sourcePreview = useMemo(() => labelFile ? URL.createObjectURL(labelFile) : '', [labelFile]);
  const load = useCallback(async () => {
    const [results, preferences] = await Promise.all([repositories.foods.search(query), repositories.foodPreferences.listForProfile(profile.id)]);
    setFoods(results); setFavorites(new Set(preferences.filter((item) => item.favorite).map((item) => item.foodId)));
  }, [profile.id, query]);
  useEffect(() => { queueMicrotask(() => void load()); }, [load, revision]);
  function update(key: keyof FoodDraft, value: string) { setDraft((current) => ({ ...current, [key]: value })); }
  useEffect(() => () => { if (labelPreview) URL.revokeObjectURL(labelPreview); }, [labelPreview]);
  useEffect(() => () => { if (sourcePreview) URL.revokeObjectURL(sourcePreview); }, [sourcePreview]);
  function open(kind: 'manual' | 'ocr') { setDraft(emptyFood); setLabelFile(undefined); setLabelMedia(undefined); setOcrText(''); setOcrManualMode(false); setOcrWarnings([]); setOcrTimings(undefined); setOcrColumns(undefined); setOcrPortion(undefined); setOcrBasis('portion'); setRotation(0); setCropInset(0); setEnhanceOcr(true); setKeepLabelPhoto(false); setError(''); setDuplicates([]); setPortionLabel(''); setPortionEquivalent(''); setEditor(kind); }
  function selectLabel(event: ChangeEvent<HTMLInputElement>) {
    const file = event.target.files?.[0]; if (!file) return;
    setLabelFile(file); setLabelMedia(undefined); setOcrText(''); setOcrWarnings([]); setOcrTimings(undefined); setError(''); event.target.value = '';
  }
  function applyParsedNutrients(values: NutrientValues, quantity?: number, unit?: PortionUnit) {
    setDraft((current) => ({ ...current, quantity: quantity === undefined ? current.quantity : String(quantity), unit: unit ?? current.unit,
      calories: values.caloriesKcal === undefined ? '' : String(values.caloriesKcal), protein: values.proteinGrams === undefined ? '' : String(values.proteinGrams), carbs: values.carbsGrams === undefined ? '' : String(values.carbsGrams), fat: values.fatGrams === undefined ? '' : String(values.fatGrams), fiber: values.fiberGrams === undefined ? '' : String(values.fiberGrams), sodium: values.sodiumMg === undefined ? '' : String(values.sodiumMg), saturatedFat: values.saturatedFatGrams === undefined ? '' : String(values.saturatedFatGrams), sugars: values.sugarsGrams === undefined ? '' : String(values.sugarsGrams), addedSugars: values.addedSugarsGrams === undefined ? '' : String(values.addedSugarsGrams) }));
  }
  async function processLabel() {
    if (!labelFile) return;
    try {
      const attemptStarted = performance.now(); let imageTimings: ImageProcessingTimings | undefined;
      setBusy('Preparando imagem…'); const media = await optimizeImage(labelFile, 'nutrition-label', 'food', undefined, crypto.randomUUID(), new Date(), { rotationQuarterTurns: rotation, cropInsetPercent: cropInset, enhanceForOcr: enhanceOcr, maxDimension: 2000, onTiming: (value) => { imageTimings = value; } }); setLabelMedia(media);
      setBusy('Carregando OCR local…'); const result = await recognizeNutritionLabel(media.blob, (progress) => setBusy(describeOcrProgress(progress)));
      setBusy('Organizando nutrientes…'); const parserStarted = performance.now(); const parsed = parseBrazilianNutritionLabel(result.text); const parserMs = performance.now() - parserStarted; setOcrText(result.text); setOcrTimings({ ...result.timings, image: imageTimings, parserMs, totalAttemptMs: performance.now() - attemptStarted });
      setOcrWarnings(parsed.warnings); setOcrColumns(parsed.columns); setOcrPortion(parsed.portion); setOcrBasis(parsed.columns?.portion ? 'portion' : 'per100');
      applyParsedNutrients(parsed.nutrients, parsed.portion?.quantity, parsed.portion?.unit);
      setAdvanced(true); setBusy('');
    } catch (caught) { setBusy(''); setError(caught instanceof Error ? caught.message : 'Não foi possível ler esta imagem.'); }
  }
  async function persistFood(forceDuplicate = false) {
    setError(''); setBusy('Salvando…');
    try {
      if (!forceDuplicate) {
        const candidates = await repositories.foods.search(draft.barcode || draft.name, 12);
        const matches = candidates.filter((item) => (draft.barcode && item.barcode === draft.barcode) || (item.nameNormalized === normalizeFoodSearch(draft.name) && normalizeFoodSearch(item.brand ?? '') === normalizeFoodSearch(draft.brand)));
        if (matches.length) { setDuplicates(matches); setBusy(''); return; }
      }
      const foodId = crypto.randomUUID();
      const result = await foodService.save({ id: foodId, name: draft.name, brand: draft.brand, category: draft.category, barcode: draft.barcode, baseQuantity: Number(draft.quantity), baseUnit: draft.unit,
        nutrients: { caloriesKcal: number(draft.calories), proteinGrams: number(draft.protein), carbsGrams: number(draft.carbs), fatGrams: number(draft.fat), fiberGrams: number(draft.fiber), sodiumMg: number(draft.sodium), saturatedFatGrams: number(draft.saturatedFat), sugarsGrams: number(draft.sugars), addedSugarsGrams: number(draft.addedSugars) },
        portions: portionLabel.trim() && Number(portionEquivalent) > 0 ? [{ id: crypto.randomUUID(), label: portionLabel.trim(), quantity: 1, unit: 'unit', equivalentBaseQuantity: Number(portionEquivalent) }] : [], dataSource: editor === 'ocr' && Boolean(ocrText) ? 'nutrition-label-ocr' : 'manual', nutritionLabelPhotoRef: keepLabelPhoto ? labelMedia?.id : undefined });
      if (labelMedia && keepLabelPhoto) await repositories.media.save({ ...labelMedia, ownerId: result.food.id });
      setEditor(undefined); await load(); onChanged(); onNotice(result.duplicates.length ? 'Alimento salvo. Encontramos um item semelhante para você conferir.' : 'Alimento salvo no catálogo compartilhado.');
    } catch (caught) { setError(caught instanceof Error ? caught.message : 'Não foi possível salvar o alimento.'); } finally { setBusy(''); }
  }
  async function save(event: FormEvent) { event.preventDefault(); await persistFood(false); }
  async function toggleFavorite(food: Food) {
    const existing = await repositories.foodPreferences.get(profile.id, food.id); const timestamp = new Date().toISOString();
    await repositories.foodPreferences.save({ id: existing?.id ?? `${profile.id}:${food.id}`, profileId: profile.id, foodId: food.id, favorite: !existing?.favorite, useCount: existing?.useCount ?? 0, lastUsedAt: existing?.lastUsedAt, createdAt: existing?.createdAt ?? timestamp, updatedAt: timestamp });
    await load(); onNotice(existing?.favorite ? 'Removido dos favoritos.' : 'Adicionado aos favoritos deste perfil.');
  }
  return <Page title="Alimentos" eyebrow="Catálogo compartilhado" actions={<><button className="secondary-action" onClick={() => open('ocr')}>Fotografar tabela</button><button className="primary-action" onClick={() => open('manual')}>+ Novo alimento</button></>}>
    <div className="catalog-toolbar"><label><span>Buscar no catálogo</span><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Nome, marca, categoria ou código" /></label><small>{foods.length} resultado(s) · favoritos são pessoais</small></div>
    {foods.length ? <div className="food-grid">{foods.map((food) => <article className="food-card" key={food.id}><button className="favorite-button" aria-label={favorites.has(food.id) ? 'Remover dos favoritos' : 'Favoritar alimento'} onClick={() => void toggleFavorite(food)}>{favorites.has(food.id) ? '★' : '☆'}</button><span className="origin-pill">{food.dataSource === 'nutrition-label-ocr' ? 'OCR revisado' : 'Manual'}</span><h2>{food.name}</h2><p>{food.brand || food.category || 'Sem marca'}</p><strong>{show(food.nutrients.caloriesKcal, ' kcal')}</strong><MacroLegend proteinGrams={food.nutrients.proteinGrams} carbsGrams={food.nutrients.carbsGrams} fatGrams={food.nutrients.fatGrams} /><small>por {food.basePortion.quantity} {food.basePortion.unit}</small></article>)}</div> : <Empty title="Seu catálogo começa aqui." copy="Cadastre manualmente ou fotografe a tabela nutricional de um produto." actions={<><button onClick={() => open('ocr')}>Fotografar tabela</button><button onClick={() => open('manual')}>Cadastrar alimento</button></>} />}
    {editor && <Modal title={editor === 'ocr' ? 'Ler tabela nutricional' : 'Novo alimento'} onClose={() => { if (busy) void cancelNutritionLabelRecognition(); setEditor(undefined); }}><form className="food-form" onSubmit={(event) => void save(event)}>
      {editor === 'ocr' && <div className="camera-zone"><strong>Escolha de onde vem a tabela nutricional.</strong><p>O formulário só aparece depois da leitura ou se você optar pelo preenchimento manual.</p><div className="camera-source-actions"><button type="button" onClick={() => cameraInput.current?.click()}>{labelFile ? 'Trocar pela câmera' : 'Tirar foto'}</button><button type="button" onClick={() => galleryInput.current?.click()}>{labelFile ? 'Trocar pela galeria' : 'Escolher da galeria'}</button></div><input ref={cameraInput} className="sr-only" aria-label="Tirar foto da tabela nutricional" type="file" accept="image/*" capture="environment" onChange={selectLabel} /><input ref={galleryInput} className="sr-only" aria-label="Escolher tabela nutricional da galeria" type="file" accept="image/jpeg,image/png,image/webp" onChange={selectLabel} />{!capabilities.camera && <small>A captura depende do suporte do navegador; a galeria permanece disponível.</small>}{!labelFile && !ocrManualMode && <button className="ocr-manual-button" type="button" onClick={() => setOcrManualMode(true)}>Preencher manualmente</button>}{(labelPreview || sourcePreview) && <button className="label-preview-button" type="button" onClick={() => setPreviewZoom(true)} aria-label="Ampliar imagem da tabela"><img className="label-preview" style={!labelMedia ? { transform: `rotate(${rotation * 90}deg)` } : undefined} src={labelPreview || sourcePreview} alt="Prévia do rótulo selecionado" /><span>Toque para ampliar</span></button>}{labelFile && !ocrText && <div className="ocr-preparation"><button type="button" onClick={() => setRotation((value) => ((value + 1) % 4) as 0|1|2|3)}>Girar 90°</button><label>Recortar bordas <b>{cropInset}%</b><input type="range" min="0" max="20" step="2" value={cropInset} onChange={(event) => setCropInset(Number(event.target.value))} /></label><label className="ocr-enhance"><input type="checkbox" checked={enhanceOcr} onChange={(event) => setEnhanceOcr(event.target.checked)} /> Contraste leve para texto</label><button className="ocr-read-button" type="button" disabled={Boolean(busy)} onClick={() => void processLabel()}>Ler tabela</button></div>}{busy && <div className="ocr-live" role="status"><span>{busy}</span><button type="button" onClick={() => { void cancelNutritionLabelRecognition(); setBusy(''); }}>Cancelar</button></div>}</div>}
      {editor === 'ocr' && ocrText && <aside className="review-note"><strong>Revisão obrigatória</strong><span>O OCR é um rascunho: campos não detectados ficam vazios. Confira a imagem e cada valor antes de salvar.</span>{ocrColumns?.portion && ocrColumns.per100 && <div className="ocr-basis"><button type="button" className={ocrBasis === 'portion' ? 'active' : ''} onClick={() => { setOcrBasis('portion'); applyParsedNutrients(ocrColumns.portion ?? {}, ocrPortion?.quantity, ocrPortion?.unit); }}>Usar coluna da porção</button><button type="button" className={ocrBasis === 'per100' ? 'active' : ''} onClick={() => { setOcrBasis('per100'); applyParsedNutrients(ocrColumns.per100 ?? {}, 100, ocrPortion?.unit === 'ml' ? 'ml' : 'g'); }}>Usar coluna de 100 {ocrPortion?.unit === 'ml' ? 'ml' : 'g'}</button></div>}{ocrWarnings.map((warning) => <small key={warning}>{warning}</small>)}{ocrTimings && <small>Tempo total: {(ocrTimings.totalAttemptMs / 1000).toFixed(2)} s · imagem {(ocrTimings.image?.totalMs ?? 0).toFixed(0)} ms (decode {(ocrTimings.image?.decodeMs ?? 0).toFixed(0)} ms, ajuste {(ocrTimings.image?.transformMs ?? 0).toFixed(0)} ms, WebP {(ocrTimings.image?.encodeMs ?? 0).toFixed(0)} ms) · motor {(ocrTimings.workerLoadMs / 1000).toFixed(2)} s · leitura {(ocrTimings.recognizeMs / 1000).toFixed(2)} s · parser {ocrTimings.parserMs.toFixed(1)} ms · {ocrTimings.reusedWorker ? 'worker reutilizado' : 'worker carregado agora'}.</small>}<label className="keep-label-photo"><input type="checkbox" checked={keepLabelPhoto} onChange={(event) => setKeepLabelPhoto(event.target.checked)} /> Guardar a imagem otimizada junto do alimento</label></aside>}
      {(editor === 'manual' || Boolean(ocrText) || ocrManualMode) && <><fieldset className="food-form-section"><legend>Produto</legend><div className="form-grid"><Field label="Nome do produto" value={draft.name} onChange={(value) => update('name', value)} required /><Field label="Marca" value={draft.brand} onChange={(value) => update('brand', value)} /></div></fieldset>
      <fieldset className="food-form-section"><legend>Porção</legend><div className="form-grid"><Field label="Quantidade" value={draft.quantity} onChange={(value) => update('quantity', value)} type="number" required /><label>Unidade<DefynSelect label="Unidade da porção" value={draft.unit} onChange={(value) => update('unit', value)} options={[{ value: 'g', label: 'Gramas (g)' }, { value: 'ml', label: 'Mililitros (ml)' }, { value: 'unit', label: 'Unidade' }, { value: 'slice', label: 'Fatia' }, { value: 'scoop', label: 'Scoop' }]} /></label></div></fieldset>
      <fieldset className="food-form-section"><legend>Macronutrientes</legend><div className="form-grid"><Field label="Calorias (kcal)" value={draft.calories} onChange={(value) => update('calories', value)} type="number" /><Field label="Proteína (g)" value={draft.protein} onChange={(value) => update('protein', value)} type="number" /><Field label="Carboidratos (g)" value={draft.carbs} onChange={(value) => update('carbs', value)} type="number" /><Field label="Gorduras (g)" value={draft.fat} onChange={(value) => update('fat', value)} type="number" /></div></fieldset>
      <button className="details-toggle" type="button" onClick={() => setAdvanced((value) => !value)}>{advanced ? 'Ocultar informações adicionais' : 'Mais informações'}</button>{advanced && <fieldset className="food-form-section"><legend>Informações adicionais</legend><div className="form-grid"><Field label="Categoria" value={draft.category} onChange={(value) => update('category', value)} /><Field label="Código de barras" value={draft.barcode} onChange={(value) => update('barcode', value)} /><Field label="Fibra (g)" value={draft.fiber} onChange={(value) => update('fiber', value)} type="number" /><Field label="Sódio (mg)" value={draft.sodium} onChange={(value) => update('sodium', value)} type="number" /><Field label="Gordura saturada (g)" value={draft.saturatedFat} onChange={(value) => update('saturatedFat', value)} type="number" /><Field label="Açúcares totais (g)" value={draft.sugars} onChange={(value) => update('sugars', value)} type="number" /><Field label="Açúcares adicionados (g)" value={draft.addedSugars} onChange={(value) => update('addedSugars', value)} type="number" /><Field label="Porção conveniente (ex.: 1 fatia)" value={portionLabel} onChange={setPortionLabel} /><Field label={`Equivale a quantos ${draft.unit}`} value={portionEquivalent} onChange={setPortionEquivalent} type="number" /></div></fieldset>}
      {duplicates.length > 0 && <aside className="duplicate-warning"><strong>Este alimento parece já estar cadastrado.</strong>{duplicates.map((food) => <span key={food.id}>{food.name}{food.brand ? ` · ${food.brand}` : ''}</span>)}<div><button type="button" onClick={() => setEditor(undefined)}>Usar existente</button><button type="button" onClick={() => void persistFood(true)}>Salvar mesmo assim</button></div></aside>}
      {error && <p className="inline-error" role="alert">{error}</p>}<button className="primary-action full form-save-action" disabled={Boolean(busy)}>{busy || (editor === 'ocr' && ocrText ? 'Confirmar e salvar' : 'Salvar alimento')}</button></>}</form>{previewZoom && <div className="label-zoom-backdrop" role="dialog" aria-modal="true" aria-label="Imagem ampliada da tabela"><button type="button" onClick={() => setPreviewZoom(false)} aria-label="Fechar imagem ampliada">×</button><img src={labelPreview || sourcePreview} alt="Tabela nutricional ampliada" /></div>}</Modal>}
  </Page>;
}

function DiaryPage({ profile, revision, onChanged, onNotice }: { profile: UserProfile; revision: number; onChanged: () => void; onNotice: (message: string) => void }) {
  const [date, setDate] = useState(toLocalDateKey(new Date())); const [meals, setMeals] = useState<MealCategory[]>([]); const [entries, setEntries] = useState<DiaryEntry[]>([]); const [adding, setAdding] = useState<MealCategory>(); const [foods, setFoods] = useState<Food[]>([]); const [selectedFood, setSelectedFood] = useState<Food>(); const [quantity, setQuantity] = useState('100'); const [newMeal, setNewMeal] = useState(''); const [undo, setUndo] = useState<DiaryEntry>(); const [favoriteMeals, setFavoriteMeals] = useState<FavoriteMeal[]>([]);
  const load = useCallback(async () => { const categories = await diaryService.ensureDefaultMeals(profile.id); const [records, favorites] = await Promise.all([repositories.diary.listEntries(profile.id, date), repositories.diary.listFavoriteMeals?.(profile.id) ?? Promise.resolve([])]); setMeals(categories.filter((item) => !item.hidden)); setEntries(records); setFavoriteMeals(favorites); }, [date, profile.id]);
  useEffect(() => { queueMicrotask(() => void load()); }, [load, revision]); const totals = totalDiaryNutrients(entries);
  function shift(days: number) { const value = new Date(`${date}T12:00:00`); value.setDate(value.getDate() + days); setDate(toLocalDateKey(value)); }
  async function openAdd(meal: MealCategory) { setAdding(meal); setSelectedFood(undefined); setFoods(await repositories.foods.search('')); }
  async function add() { if (!adding || !selectedFood) return; await diaryService.addFood(profile.id, date, adding.id, selectedFood, Number(quantity)); setAdding(undefined); await load(); onChanged(); onNotice(`Adicionado a ${adding.name}.`); }
  async function remove(entry: DiaryEntry) { await repositories.diary.removeEntry(entry.id); setUndo(entry); await load(); onChanged(); }
  async function restore() { if (!undo) return; await repositories.diary.saveEntry(undo); setUndo(undefined); await load(); onChanged(); onNotice('Item restaurado.'); }
  async function addMeal(event: FormEvent) { event.preventDefault(); if (!newMeal.trim()) return; const timestamp = new Date().toISOString(); await repositories.diary.saveMealCategory({ id: crypto.randomUUID(), profileId: profile.id, name: newMeal.trim(), order: meals.length, hidden: false, createdAt: timestamp, updatedAt: timestamp }); setNewMeal(''); await load(); }
  async function favoriteMeal(meal: MealCategory, items: DiaryEntry[]) { if (!items.length || !repositories.diary.saveFavoriteMeal) return; const timestamp = new Date().toISOString(); await repositories.diary.saveFavoriteMeal({ id: crypto.randomUUID(), profileId: profile.id, name: meal.name, mealCategoryName: meal.name, items: items.map((entry) => ({ ...entry.item, nutrients: { ...entry.item.nutrients } })), createdAt: timestamp, updatedAt: timestamp }); await load(); onNotice('Refeição favorita salva.'); }
  async function applyFavorite(favorite: FavoriteMeal) { const meal = meals.find((item) => item.name === favorite.mealCategoryName) ?? meals[0]; if (!meal) return; const timestamp = new Date().toISOString(); await Promise.all(favorite.items.map((item) => repositories.diary.saveEntry({ id: crypto.randomUUID(), profileId: profile.id, date, mealCategoryId: meal.id, time: timestamp.slice(11,16), item: { ...item, nutrients: { ...item.nutrients } }, createdAt: timestamp, updatedAt: timestamp }))); await load(); onChanged(); onNotice(`${favorite.name} adicionado ao diário.`); }
  async function copyYesterday(meal: MealCategory) { const yesterday = new Date(`${date}T12:00:00`); yesterday.setDate(yesterday.getDate() - 1); const previous = await repositories.diary.listEntries(profile.id, toLocalDateKey(yesterday)); const items = previous.filter((entry) => entry.mealCategoryId === meal.id); if (!items.length) { onNotice('Não há itens nessa refeição ontem.'); return; } const timestamp = new Date().toISOString(); await Promise.all(items.map((entry) => repositories.diary.saveEntry({ ...entry, id: crypto.randomUUID(), date, createdAt: timestamp, updatedAt: timestamp }))); await load(); onChanged(); onNotice(`${meal.name} copiado de ontem.`); }
  return <Page title="Diário" eyebrow="Consumo por pessoa e dia" actions={<div className="date-nav"><button aria-label="Dia anterior" onClick={() => shift(-1)}>←</button><button onClick={() => setDate(toLocalDateKey(new Date()))}>Hoje</button><button aria-label="Próximo dia" onClick={() => shift(1)}>→</button></div>}>
    <div className="diary-summary"><div><span>{new Intl.DateTimeFormat('pt-BR', { weekday: 'long', day: '2-digit', month: 'long' }).format(new Date(`${date}T12:00:00`))}</span><strong>{show(totals.caloriesKcal, ' kcal')}</strong></div><div><MacroLegend proteinGrams={totals.proteinGrams} carbsGrams={totals.carbsGrams} fatGrams={totals.fatGrams} stacked /></div></div>
    {favoriteMeals.length > 0 && <div className="favorite-meals"><strong>Refeições favoritas</strong>{favoriteMeals.map((favorite) => <button key={favorite.id} onClick={() => void applyFavorite(favorite)}>+ {favorite.name}</button>)}</div>}
    <div className="meal-stack">{meals.map((meal) => { const items = entries.filter((entry) => entry.mealCategoryId === meal.id); const nutrients = totalDiaryNutrients(items); return <article className="meal-card" key={meal.id}><header><div><span>{meal.approximateTime || 'Horário livre'}</span><h2>{meal.name}</h2></div><strong>{show(nutrients.caloriesKcal, ' kcal')}</strong></header>{items.length ? <ul>{items.map((entry) => <li key={entry.id}><div><strong>{entry.item.displayName}</strong><span>{entry.item.consumedQuantity} {entry.item.consumedUnit} · {show(entry.item.nutrients.caloriesKcal, ' kcal')}</span></div><input aria-label={`Quantidade de ${entry.item.displayName}`} type="number" value={entry.item.consumedQuantity} onChange={async (event) => { await diaryService.updateQuantity(entry, Number(event.target.value)); await load(); onChanged(); }} /><DefynSelect label={`Mover ${entry.item.displayName}`} value={entry.mealCategoryId} onChange={(value) => void (async () => { await diaryService.move(entry, value); await load(); onChanged(); })()} options={meals.map((target) => ({ value: target.id, label: target.name }))} /><button aria-label={`Remover ${entry.item.displayName}`} onClick={() => void remove(entry)}>×</button></li>)}</ul> : <p>Nenhum consumo registrado.</p>}<footer><MacroLegend proteinGrams={nutrients.proteinGrams} carbsGrams={nutrients.carbsGrams} fatGrams={nutrients.fatGrams} /><div><button onClick={() => void copyYesterday(meal)}>Copiar ontem</button>{items.length > 0 && <button onClick={() => void favoriteMeal(meal, items)}>Favoritar</button>}<button onClick={() => void openAdd(meal)}>+ Adicionar alimento</button></div></footer></article>; })}</div>
    <form className="new-meal" onSubmit={(event) => void addMeal(event)}><input value={newMeal} onChange={(event) => setNewMeal(event.target.value)} placeholder="Nova refeição, ex.: Pré-treino" /><button>Adicionar refeição</button></form>
    {undo && <div className="undo-bar" role="status"><span>Item removido.</span><button onClick={() => void restore()}>Desfazer</button></div>}
    {adding && <Modal className="meal-picker-modal" title={`Adicionar ao ${adding.name}`} onClose={() => setAdding(undefined)}><div className="meal-picker-content"><label className="modal-search">Buscar alimento<input autoFocus onChange={async (event) => setFoods(await repositories.foods.search(event.target.value))} placeholder="Digite nome, marca ou código" /></label><div className="picker-list" aria-label="Resultados da busca">{foods.map((food) => <button type="button" className={selectedFood?.id === food.id ? 'selected' : ''} aria-pressed={selectedFood?.id === food.id} key={food.id} onClick={() => { setSelectedFood(food); setQuantity(String(food.basePortion.quantity)); }}><span><strong>{food.name}</strong><small>{food.brand || `${food.basePortion.quantity} ${food.basePortion.unit}`}</small><em>P {show(food.nutrients.proteinGrams, ' g')} · C {show(food.nutrients.carbsGrams, ' g')} · G {show(food.nutrients.fatGrams, ' g')}</em></span><b>{show(food.nutrients.caloriesKcal, ' kcal')}</b></button>)}</div>{selectedFood && <section className="quantity-preview" aria-label="Alimento selecionado"><header><span>Item selecionado</span><strong>{selectedFood.name}</strong></header><label>Quantidade <small>{selectedFood.basePortion.unit}</small><input type="number" min="0.1" step="0.1" value={quantity} onChange={(event) => setQuantity(event.target.value)} /></label><div><span>Resumo nutricional</span><strong>{show(scaleNutrients(selectedFood.nutrients, selectedFood.basePortion.quantity, Number(quantity)).caloriesKcal, ' kcal')}</strong><small>P {show(scaleNutrients(selectedFood.nutrients, selectedFood.basePortion.quantity, Number(quantity)).proteinGrams, ' g')} · C {show(scaleNutrients(selectedFood.nutrients, selectedFood.basePortion.quantity, Number(quantity)).carbsGrams, ' g')} · G {show(scaleNutrients(selectedFood.nutrients, selectedFood.basePortion.quantity, Number(quantity)).fatGrams, ' g')}</small></div></section>}<button type="button" className="primary-action full meal-picker-submit" disabled={!selectedFood || Number(quantity) <= 0} onClick={() => void add()}>Adicionar à refeição</button></div></Modal>}
  </Page>;
}

function RecipesPage({ profile, revision, onChanged, onNotice }: { profile: UserProfile; revision: number; onChanged: () => void; onNotice: (message: string) => void }) {
  const [recipes, setRecipes] = useState<Recipe[]>([]); const [foods, setFoods] = useState<Food[]>([]); const [open, setOpen] = useState(false); const [name, setName] = useState(''); const [servings, setServings] = useState('4'); const [ingredients, setIngredients] = useState<{ foodId: string; quantity: string }[]>([]);
  const load = useCallback(async () => { setRecipes(await repositories.recipes.list()); setFoods(await repositories.foods.list()); }, []); useEffect(() => { queueMicrotask(() => void load()); }, [load, revision]);
  const nutrition = useMemo(() => calculateRecipeNutrition(ingredients.flatMap((item) => { const food = foods.find((candidate) => candidate.id === item.foodId); return food ? [{ foodId: food.id, foodName: food.name, quantity: Number(item.quantity), unit: food.basePortion.unit, nutrientSnapshot: scaleNutrients(food.nutrients, food.basePortion.quantity, Number(item.quantity)) }] : []; }), Number(servings) || 1), [foods, ingredients, servings]);
  async function save(event: FormEvent) { event.preventDefault(); if (!name.trim() || !ingredients.length) return; const timestamp = new Date().toISOString(); const items = ingredients.flatMap((item) => { const food = foods.find((candidate) => candidate.id === item.foodId); return food ? [{ foodId: food.id, foodName: food.name, quantity: Number(item.quantity), unit: food.basePortion.unit, nutrientSnapshot: scaleNutrients(food.nutrients, food.basePortion.quantity, Number(item.quantity)) }] : []; }); const recipe: Recipe = { id: crypto.randomUUID(), name: name.trim(), nameNormalized: normalizeFoodSearch(name), ingredients: items, servings: Number(servings), yieldDescription: `${servings} porções`, nutritionSnapshot: calculateRecipeNutrition(items, Number(servings)), createdAt: timestamp, updatedAt: timestamp }; await repositories.recipes.save(recipe); setOpen(false); setName(''); setIngredients([]); await load(); onChanged(); onNotice('Receita salva com nutrientes por porção.'); }
  async function addRecipe(recipe: Recipe) { if (!recipe.nutritionSnapshot) return; const categories = await diaryService.ensureDefaultMeals(profile.id); const meal = categories[0]; if (!meal) return; const timestamp = new Date().toISOString(); await repositories.diary.saveEntry({ id: crypto.randomUUID(), profileId: profile.id, date: toLocalDateKey(new Date()), mealCategoryId: meal.id, time: timestamp.slice(11,16), item: { sourceType:'recipe', sourceId:recipe.id, sourceUpdatedAt:recipe.updatedAt, displayName:recipe.name, consumedQuantity:1, consumedUnit:'portion', nutrients:{...recipe.nutritionSnapshot.perServing} }, createdAt:timestamp, updatedAt:timestamp }); onChanged(); onNotice(`1 porção de ${recipe.name} adicionada a ${meal.name}.`); }
  return <Page title="Receitas" eyebrow="Preparações reutilizáveis" actions={<button className="primary-action" onClick={() => setOpen(true)}>+ Nova receita</button>}>{recipes.length ? <div className="recipe-grid">{recipes.map((recipe) => <article key={recipe.id}><span>{recipe.servings} porções</span><h2>{recipe.name}</h2><strong>{show(recipe.nutritionSnapshot?.perServing.caloriesKcal, ' kcal')}</strong><p>por porção · snapshot preservado ao registrar</p><MacroLegend proteinGrams={recipe.nutritionSnapshot?.perServing.proteinGrams} carbsGrams={recipe.nutritionSnapshot?.perServing.carbsGrams} fatGrams={recipe.nutritionSnapshot?.perServing.fatGrams} /><button className="recipe-add" onClick={() => void addRecipe(recipe)}>Adicionar 1 porção ao diário</button></article>)}</div> : <Empty title="Transforme ingredientes em receitas." copy="Cadastre uma preparação, seu rendimento e reutilize porções no diário." actions={<button onClick={() => setOpen(true)}>Criar receita</button>} />}{open && <Modal title="Nova receita" onClose={() => setOpen(false)}><form className="recipe-form" onSubmit={(event) => void save(event)}><Field label="Nome da receita" value={name} onChange={setName} required /><Field label="Número de porções" value={servings} onChange={setServings} type="number" required /><label>Adicionar ingrediente<DefynSelect label="Adicionar ingrediente" value="" onChange={(value) => { if (value) setIngredients((current) => [...current, { foodId: value, quantity: '100' }]); }} options={[{ value: '', label: 'Escolha do catálogo' }, ...foods.map((food) => ({ value: food.id, label: food.name }))]} /></label><div className="ingredient-list">{ingredients.map((item, index) => { const food = foods.find((candidate) => candidate.id === item.foodId); return <div key={`${item.foodId}-${index}`}><span>{food?.name}</span><input aria-label={`Quantidade de ${food?.name}`} type="number" value={item.quantity} onChange={(event) => setIngredients((current) => current.map((candidate, currentIndex) => currentIndex === index ? { ...candidate, quantity: event.target.value } : candidate))} /><small>{food?.basePortion.unit}</small><button type="button" onClick={() => setIngredients((current) => current.filter((_, currentIndex) => currentIndex !== index))}>×</button></div>; })}</div><aside className="recipe-preview"><span>Total: {show(nutrition.total.caloriesKcal, ' kcal')}</span><strong>Por porção: {show(nutrition.perServing.caloriesKcal, ' kcal')}</strong></aside><button className="primary-action full">Salvar receita</button></form></Modal>}</Page>;
}

function PlannerPage({ profile, revision }: { profile: UserProfile; revision: number }) {
  const [foods, setFoods] = useState<Food[]>([]); const [target, setTarget] = useState<Awaited<ReturnType<typeof repositories.nutritionTargets.getActiveForProfile>>>(); const [preset, setPreset] = useState<'balanced' | 'main-meals-larger'>((profile.nutritionPlanning?.mealSizePreference === 'main-meals-larger' ? 'main-meals-larger' : 'balanced'));
  useEffect(() => { void Promise.all([repositories.foods.list(), repositories.nutritionTargets.getActiveForProfile(profile.id)]).then(([catalog, active]) => { setFoods(catalog); setTarget(active); }); }, [profile.id, revision]);
  if (!target) return <div className="page-container">Carregando planejamento…</div>;
  const mealNames = ['Café da manhã', 'Almoço', 'Lanche', 'Jantar'].slice(0, profile.nutritionPlanning?.mealsPerDay ?? 4); const result = planDailyMeals({ target: { caloriesKcal: target.result.calorieTarget, proteinGrams: target.result.macros.protein.grams, carbsGrams: target.result.macros.carbs.grams, fatGrams: target.result.macros.fat.grams }, mealNames, mealTimes: profile.nutritionPlanning?.mealTimes, preset, foods, restrictions: [...(profile.nutritionPlanning?.dietaryRestrictions ?? []), ...(profile.nutritionPlanning?.intolerances ?? []), ...(profile.nutritionPlanning?.allergies ?? []), ...(profile.nutritionPlanning?.avoidedFoods ?? [])] });
  return <Page title="Planejamento" eyebrow="Motor determinístico e explicável" actions={<DefynSelect label="Distribuição das refeições" value={preset} onChange={setPreset} options={[{ value: 'balanced', label: 'Equilibrado' }, { value: 'main-meals-larger', label: 'Almoço/jantar maiores' }]} />}><aside className="planner-disclaimer"><strong>Meta, não prescrição.</strong><span>O DEFYN distribui matematicamente suas metas e filtra o catálogo pelas informações que você forneceu. Ajuste as sugestões à sua rotina.</span></aside><div className="target-grid">{result.targets.map((meal) => <article key={meal.name}><span>{meal.time || 'Horário livre'} · {Math.round(meal.ratio * 100)}%</span><h2>{meal.name}</h2><strong>~{Math.round(meal.nutrients.caloriesKcal)} kcal</strong><MacroLegend proteinGrams={meal.nutrients.proteinGrams} carbsGrams={meal.nutrients.carbsGrams} fatGrams={meal.nutrients.fatGrams} /></article>)}</div><section className="planner-catalog"><div><span className="page-eyebrow">Base disponível</span><h2>{result.compatibleFoods.length} alimento(s) compatível(is)</h2><p>{result.metadata.explanation}</p></div>{result.warnings.map((warning) => <p className="planner-warning" key={warning}>{warning}</p>)}</section></Page>;
}

function Page({ title, eyebrow, actions, children }: { title: string; eyebrow: string; actions?: React.ReactNode; children: React.ReactNode }) { const descriptions: Record<string,string> = { Alimentos: 'Cadastre, revise e reutilize alimentos sem enviar seus dados.', Diário: 'Registre refeições e acompanhe o total do dia.', Receitas: 'Monte preparações e reutilize porções no Diário.', Planejamento: 'Distribua suas metas de forma explicável e ajustável.' }; return <div className="nutrition-page page-container"><header className="nutrition-header"><div><span className="page-eyebrow">{eyebrow}</span><h1>{title}</h1><p>{descriptions[title]}</p></div><div>{actions}</div></header>{children}</div>; }
function Modal({ title, className = '', onClose, children }: { title: string; className?: string; onClose: () => void; children: React.ReactNode }) { const closeRef = useRef<HTMLButtonElement>(null); const onCloseRef = useRef(onClose); useEffect(() => { onCloseRef.current = onClose; }, [onClose]); useEffect(() => { const trigger = document.activeElement instanceof HTMLElement ? document.activeElement : undefined; closeRef.current?.focus(); const keydown = (event: KeyboardEvent) => { if (event.key === 'Escape') onCloseRef.current(); }; document.addEventListener('keydown', keydown); return () => { document.removeEventListener('keydown', keydown); trigger?.focus(); }; }, []); return <div className="nutrition-modal-backdrop" onMouseDown={(event) => { if (event.target === event.currentTarget) onClose(); }}><section className={`nutrition-modal${className ? ` ${className}` : ''}`} role="dialog" aria-modal="true" aria-label={title}><header><h2>{title}</h2><button ref={closeRef} onClick={onClose} aria-label="Fechar">×</button></header>{children}</section></div>; }
function Field({ label, value, onChange, type = 'text', required = false }: { label: string; value: string; onChange: (value: string) => void; type?: string; required?: boolean }) { return <label>{label}<input type={type} inputMode={type === 'number' ? 'decimal' : undefined} min={type === 'number' ? '0' : undefined} step={type === 'number' ? '0.1' : undefined} value={value} onChange={(event) => onChange(event.target.value)} required={required} /></label>; }
function Empty({ title, copy, actions }: { title: string; copy: string; actions: React.ReactNode }) { return <div className="nutrition-empty"><span aria-hidden="true">D</span><h2>{title}</h2><p>{copy}</p><div>{actions}</div></div>; }
